#define OCELOT_CORES 1
#define OCELOT_ARRAYS_SIZE 1000
#include "CBridge.h"
#define OCELOT_TYPES {}
#define EXECUTE_OCELOT_TEST t_data_state_db __arg0 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(0));\
t_data_state_db __arg1 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(1));\
t_data_state_db __arg2 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(2));\
t_data_state_db __arg3 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(3));\
t_data_state_db __arg4 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(4));\
t_data_state_db __arg5 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(5));\
t_data_state_db __arg6 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(6));\
t_data_state_db __arg7 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(7));\
t_data_state_db __arg8 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(8));\
t_data_state_db __arg9 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(9));\
t_data_state_db __arg10 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(10));\
t_data_state_db __arg11 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(11));\
t_data_state_db __arg12 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(12));\
t_data_state_db __arg13 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(13));\
t_data_state_db __arg14 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(14));\
t_data_state_db __arg15 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(15));\
t_data_state_db __arg16 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(16));\
t_data_state_db __arg17 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(17));\
t_data_state_db __arg18 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(18));\
t_data_state_db __arg19 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(19));\
t_data_state_db __arg20 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(20));\
t_data_state_db __arg21 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(21));\
t_data_state_db __arg22 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(22));\
t_data_state_db __arg23 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(23));\
t_data_state_db __arg24 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(24));\
t_data_state_db __arg25 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(25));\
t_data_state_db __arg26 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(26));\
t_data_state_db __arg27 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(27));\
t_data_state_db __arg28 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(28));\
t_data_state_db __arg29 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(29));\
t_data_state_db __arg30 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(30));\
t_data_state_db __arg31 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(31));\
t_data_state_db __arg32 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(32));\
t_data_state_db __arg33 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(33));\
t_data_state_db __arg34 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(34));\
t_data_state_db __arg35 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(35));\
t_data_state_db __arg36 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(36));\
t_data_state_db __arg37 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(37));\
t_data_state_db __arg38 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(38));\
t_data_state_db __arg39 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(39));\
t_data_state_db __arg40 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(40));\
t_data_state_db __arg41 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(41));\
t_data_state_db __arg42 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(42));\
t_data_state_db __arg43 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(43));\
t_data_state_db __arg44 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(44));\
t_data_state_db __arg45 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(45));\
t_data_state_db __arg46 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(46));\
t_data_state_db __arg47 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(47));\
t_data_state_db __arg48 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(48));\
t_data_state_db __arg49 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(49));\
t_data_state_db __arg50 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(50));\
t_data_state_db __arg51 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(51));\
t_data_state_db __arg52 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(52));\
t_data_state_db __arg53 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(53));\
t_data_state_db __arg54 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(54));\
t_data_state_db __arg55 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(55));\
t_data_state_db __arg56 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(56));\
t_data_state_db __arg57 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(57));\
t_data_state_db __arg58 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(58));\
t_data_state_db __arg59 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(59));\
t_data_state_db __arg60 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(60));\
t_data_state_db __arg61 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(61));\
t_data_state_db __arg62 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(62));\
t_data_state_db __arg63 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(63));\
t_data_state_db __arg64 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(64));\
t_data_state_db __arg65 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(65));\
t_data_state_db __arg66 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(66));\
t_data_state_db __arg67 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(67));\
t_data_state_db __arg68 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(68));\
t_data_state_db __arg69 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(69));\
t_data_state_db __arg70 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(70));\
t_data_state_db __arg71 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(71));\
t_data_state_db __arg72 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(72));\
t_data_state_db __arg73 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(73));\
t_data_state_db __arg74 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(74));\
t_data_state_db __arg75 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(75));\
t_data_state_db __arg76 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(76));\
t_data_state_db __arg77 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(77));\
t_data_state_db __arg78 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(78));\
t_data_state_db __arg79 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(79));\
t_data_state_db __arg80 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(80));\
t_data_state_db __arg81 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(81));\
t_data_state_db __arg82 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(82));\
t_data_state_db __arg83 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(83));\
t_data_state_db __arg84 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(84));\
t_data_state_db __arg85 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(85));\
t_data_state_db __arg86 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(86));\
t_data_state_db __arg87 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(87));\
t_data_state_db __arg88 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(88));\
t_data_state_db __arg89 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(89));\
t_data_state_db __arg90 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(90));\
t_data_state_db __arg91 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(91));\
t_data_state_db __arg92 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(92));\
t_data_state_db __arg93 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(93));\
t_data_state_db __arg94 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(94));\
t_data_state_db __arg95 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(95));\
t_data_state_db __arg96 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(96));\
t_data_state_db __arg97 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(97));\
t_data_state_db __arg98 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(98));\
t_data_state_db __arg99 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(99));\
t_data_state_db __arg100 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(100));\
t_data_state_db __arg101 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(101));\
t_data_state_db __arg102 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(102));\
t_data_state_db __arg103 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(103));\
t_data_state_db __arg104 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(104));\
t_data_state_db __arg105 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(105));\
t_data_state_db __arg106 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(106));\
t_data_state_db __arg107 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(107));\
t_data_state_db __arg108 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(108));\
t_data_state_db __arg109 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(109));\
t_data_state_db __arg110 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(110));\
t_data_state_db __arg111 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(111));\
t_data_state_db __arg112 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(112));\
t_data_state_db __arg113 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(113));\
t_data_state_db __arg114 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(114));\
t_data_state_db __arg115 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(115));\
t_data_state_db __arg116 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(116));\
t_data_state_db __arg117 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(117));\
t_data_state_db __arg118 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(118));\
t_data_state_db __arg119 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(119));\
t_data_state_db __arg120 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(120));\
t_data_state_db __arg121 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(121));\
t_data_state_db __arg122 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(122));\
t_data_state_db __arg123 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(123));\
t_data_state_db __arg124 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(124));\
t_data_state_db __arg125 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(125));\
t_data_state_db __arg126 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(126));\
t_data_state_db __arg127 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(127));\
t_data_state_db __arg128 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(128));\
t_data_state_db __arg129 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(129));\
t_data_state_db __arg130 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(130));\
t_data_state_db __arg131 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(131));\
t_data_state_db __arg132 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(132));\
t_data_state_db __arg133 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(133));\
t_data_state_db __arg134 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(134));\
t_data_state_db __arg135 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(135));\
t_data_state_db __arg136 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(136));\
t_data_state_db __arg137 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(137));\
t_data_state_db __arg138 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(138));\
t_data_state_db __arg139 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(139));\
t_data_state_db __arg140 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(140));\
t_data_state_db __arg141 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(141));\
t_data_state_db __arg142 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(142));\
t_data_state_db __arg143 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(143));\
t_data_state_db __arg144 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(144));\
t_data_state_db __arg145 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(145));\
t_data_state_db __arg146 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(146));\
t_data_state_db __arg147 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(147));\
t_data_state_db __arg148 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(148));\
t_data_state_db __arg149 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(149));\
t_data_state_db __arg150 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(150));\
t_data_state_db __arg151 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(151));\
t_data_state_db __arg152 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(152));\
t_data_state_db __arg153 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(153));\
t_data_state_db __arg154 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(154));\
t_data_state_db __arg155 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(155));\
t_data_state_db __arg156 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(156));\
t_data_state_db __arg157 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(157));\
t_data_state_db __arg158 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(158));\
t_data_state_db __arg159 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(159));\
t_data_id __arg160 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(160));\
t_array_index __arg161 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(161));\
t_data_id __arg162 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(162));\
t_array_index __arg163 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(163));\
t_data_id __arg164 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(164));\
t_array_index __arg165 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(165));\
t_data_id __arg166 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(166));\
t_array_index __arg167 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(167));\
t_data_id __arg168 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(168));\
t_array_index __arg169 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(169));\
t_data_id __arg170 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(170));\
t_array_index __arg171 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(171));\
t_data_id __arg172 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(172));\
t_array_index __arg173 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(173));\
t_data_id __arg174 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(174));\
t_array_index __arg175 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(175));\
t_data_id __arg176 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(176));\
t_array_index __arg177 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(177));\
t_data_id __arg178 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(178));\
t_array_index __arg179 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(179));\
t_data_id __arg180 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(180));\
t_array_index __arg181 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(181));\
t_data_id __arg182 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(182));\
t_array_index __arg183 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(183));\
t_data_id __arg184 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(184));\
t_array_index __arg185 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(185));\
t_data_id __arg186 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(186));\
t_array_index __arg187 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(187));\
t_data_id __arg188 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(188));\
t_array_index __arg189 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(189));\
t_data_id __arg190 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(190));\
t_array_index __arg191 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(191));\
t_data_id __arg192 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(192));\
t_array_index __arg193 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(193));\
t_data_id __arg194 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(194));\
t_array_index __arg195 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(195));\
t_data_id __arg196 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(196));\
t_array_index __arg197 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(197));\
t_data_id __arg198 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(198));\
t_array_index __arg199 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(199));\
t_data_id __arg200 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(200));\
t_array_index __arg201 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(201));\
t_data_id __arg202 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(202));\
t_array_index __arg203 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(203));\
t_data_id __arg204 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(204));\
t_array_index __arg205 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(205));\
t_data_id __arg206 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(206));\
t_array_index __arg207 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(207));\
t_data_id __arg208 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(208));\
t_array_index __arg209 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(209));\
t_data_id __arg210 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(210));\
t_array_index __arg211 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(211));\
t_data_id __arg212 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(212));\
t_array_index __arg213 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(213));\
t_data_id __arg214 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(214));\
t_array_index __arg215 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(215));\
t_data_id __arg216 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(216));\
t_array_index __arg217 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(217));\
t_data_id __arg218 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(218));\
t_array_index __arg219 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(219));\
t_data_id __arg220 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(220));\
t_array_index __arg221 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(221));\
t_data_id __arg222 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(222));\
t_array_index __arg223 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(223));\
t_data_id __arg224 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(224));\
t_array_index __arg225 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(225));\
t_data_id __arg226 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(226));\
t_array_index __arg227 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(227));\
t_data_id __arg228 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(228));\
t_array_index __arg229 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(229));\
t_data_id __arg230 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(230));\
t_array_index __arg231 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(231));\
t_data_id __arg232 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(232));\
t_array_index __arg233 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(233));\
t_data_id __arg234 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(234));\
t_array_index __arg235 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(235));\
t_data_id __arg236 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(236));\
t_array_index __arg237 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(237));\
t_data_id __arg238 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(238));\
t_array_index __arg239 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(239));\
t_data_id __arg240 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(240));\
t_array_index __arg241 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(241));\
t_data_id __arg242 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(242));\
t_array_index __arg243 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(243));\
t_data_id __arg244 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(244));\
t_array_index __arg245 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(245));\
t_data_id __arg246 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(246));\
t_array_index __arg247 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(247));\
t_data_id __arg248 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(248));\
t_array_index __arg249 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(249));\
t_data_id __arg250 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(250));\
t_array_index __arg251 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(251));\
t_data_id __arg252 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(252));\
t_array_index __arg253 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(253));\
t_data_id __arg254 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(254));\
t_array_index __arg255 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(255));\
t_data_id __arg256 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(256));\
t_array_index __arg257 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(257));\
t_data_id __arg258 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(258));\
t_array_index __arg259 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(259));\
t_data_id __arg260 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(260));\
t_array_index __arg261 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(261));\
t_data_id __arg262 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(262));\
t_array_index __arg263 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(263));\
t_data_id __arg264 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(264));\
t_array_index __arg265 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(265));\
t_data_id __arg266 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(266));\
t_array_index __arg267 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(267));\
t_data_id __arg268 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(268));\
t_array_index __arg269 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(269));\
t_data_id __arg270 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(270));\
t_array_index __arg271 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(271));\
t_data_id __arg272 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(272));\
t_array_index __arg273 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(273));\
t_data_id __arg274 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(274));\
t_array_index __arg275 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(275));\
t_data_id __arg276 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(276));\
t_array_index __arg277 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(277));\
t_data_id __arg278 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(278));\
t_array_index __arg279 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(279));\
t_data_id __arg280 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(280));\
t_array_index __arg281 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(281));\
t_data_id __arg282 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(282));\
t_array_index __arg283 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(283));\
t_data_id __arg284 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(284));\
t_array_index __arg285 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(285));\
t_data_id __arg286 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(286));\
t_array_index __arg287 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(287));\
t_data_id __arg288 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(288));\
t_array_index __arg289 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(289));\
t_data_id __arg290 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(290));\
t_array_index __arg291 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(291));\
t_data_id __arg292 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(292));\
t_array_index __arg293 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(293));\
t_data_id __arg294 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(294));\
t_array_index __arg295 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(295));\
t_data_id __arg296 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(296));\
t_array_index __arg297 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(297));\
t_data_id __arg298 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(298));\
t_array_index __arg299 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(299));\
t_data_id __arg300 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(300));\
t_array_index __arg301 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(301));\
t_data_id __arg302 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(302));\
t_array_index __arg303 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(303));\
t_data_id __arg304 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(304));\
t_array_index __arg305 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(305));\
t_data_id __arg306 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(306));\
t_array_index __arg307 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(307));\
t_data_id __arg308 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(308));\
t_array_index __arg309 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(309));\
t_data_id __arg310 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(310));\
t_array_index __arg311 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(311));\
t_data_id __arg312 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(312));\
t_array_index __arg313 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(313));\
t_data_id __arg314 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(314));\
t_array_index __arg315 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(315));\
t_data_id __arg316 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(316));\
t_array_index __arg317 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(317));\
t_data_id __arg318 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(318));\
t_array_index __arg319 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(319));\
t_data_id __arg320 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(320));\
t_array_index __arg321 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(321));\
t_data_id __arg322 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(322));\
t_array_index __arg323 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(323));\
t_data_id __arg324 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(324));\
t_array_index __arg325 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(325));\
t_data_id __arg326 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(326));\
t_array_index __arg327 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(327));\
t_data_id __arg328 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(328));\
t_array_index __arg329 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(329));\
t_data_id __arg330 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(330));\
t_array_index __arg331 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(331));\
t_data_id __arg332 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(332));\
t_array_index __arg333 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(333));\
t_data_id __arg334 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(334));\
t_array_index __arg335 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(335));\
t_data_id __arg336 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(336));\
t_array_index __arg337 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(337));\
t_data_id __arg338 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(338));\
t_array_index __arg339 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(339));\
t_data_id __arg340 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(340));\
t_array_index __arg341 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(341));\
t_data_id __arg342 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(342));\
t_array_index __arg343 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(343));\
t_data_id __arg344 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(344));\
t_array_index __arg345 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(345));\
t_data_id __arg346 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(346));\
t_array_index __arg347 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(347));\
t_data_id __arg348 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(348));\
t_array_index __arg349 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(349));\
t_data_id __arg350 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(350));\
t_array_index __arg351 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(351));\
t_data_id __arg352 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(352));\
t_array_index __arg353 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(353));\
t_data_id __arg354 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(354));\
t_array_index __arg355 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(355));\
t_data_id __arg356 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(356));\
t_array_index __arg357 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(357));\
t_data_id __arg358 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(358));\
t_array_index __arg359 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(359));\
t_data_id __arg360 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(360));\
t_array_index __arg361 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(361));\
t_data_id __arg362 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(362));\
t_array_index __arg363 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(363));\
t_data_id __arg364 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(364));\
t_array_index __arg365 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(365));\
t_data_id __arg366 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(366));\
t_array_index __arg367 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(367));\
t_data_id __arg368 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(368));\
t_array_index __arg369 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(369));\
t_data_id __arg370 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(370));\
t_array_index __arg371 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(371));\
t_data_id __arg372 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(372));\
t_array_index __arg373 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(373));\
t_data_id __arg374 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(374));\
t_array_index __arg375 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(375));\
t_data_id __arg376 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(376));\
t_array_index __arg377 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(377));\
t_data_id __arg378 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(378));\
t_array_index __arg379 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(379));\
t_data_id __arg380 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(380));\
t_array_index __arg381 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(381));\
t_data_id __arg382 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(382));\
t_array_index __arg383 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(383));\
t_data_id __arg384 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(384));\
t_array_index __arg385 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(385));\
t_data_id __arg386 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(386));\
t_array_index __arg387 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(387));\
t_data_id __arg388 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(388));\
t_array_index __arg389 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(389));\
t_data_id __arg390 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(390));\
t_array_index __arg391 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(391));\
t_data_id __arg392 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(392));\
t_array_index __arg393 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(393));\
t_data_id __arg394 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(394));\
t_array_index __arg395 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(395));\
t_data_id __arg396 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(396));\
t_array_index __arg397 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(397));\
t_data_id __arg398 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(398));\
t_array_index __arg399 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(399));\
t_data_id __arg400 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(400));\
t_array_index __arg401 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(401));\
t_data_id __arg402 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(402));\
t_array_index __arg403 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(403));\
t_data_id __arg404 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(404));\
t_array_index __arg405 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(405));\
t_data_id __arg406 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(406));\
t_array_index __arg407 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(407));\
t_data_id __arg408 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(408));\
t_array_index __arg409 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(409));\
t_data_id __arg410 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(410));\
t_array_index __arg411 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(411));\
t_data_id __arg412 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(412));\
t_array_index __arg413 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(413));\
t_data_id __arg414 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(414));\
t_array_index __arg415 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(415));\
t_data_id __arg416 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(416));\
t_array_index __arg417 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(417));\
t_data_id __arg418 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(418));\
t_array_index __arg419 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(419));\
t_data_id __arg420 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(420));\
t_array_index __arg421 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(421));\
t_data_id __arg422 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(422));\
t_array_index __arg423 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(423));\
t_data_id __arg424 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(424));\
t_array_index __arg425 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(425));\
t_data_id __arg426 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(426));\
t_array_index __arg427 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(427));\
t_data_id __arg428 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(428));\
t_array_index __arg429 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(429));\
t_data_id __arg430 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(430));\
t_array_index __arg431 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(431));\
t_data_id __arg432 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(432));\
t_array_index __arg433 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(433));\
t_data_id __arg434 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(434));\
t_array_index __arg435 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(435));\
t_data_id __arg436 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(436));\
t_array_index __arg437 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(437));\
t_data_id __arg438 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(438));\
t_array_index __arg439 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(439));\
t_data_id __arg440 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(440));\
t_array_index __arg441 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(441));\
t_data_id __arg442 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(442));\
t_array_index __arg443 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(443));\
t_data_id __arg444 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(444));\
t_array_index __arg445 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(445));\
t_data_id __arg446 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(446));\
t_array_index __arg447 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(447));\
t_data_id __arg448 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(448));\
t_array_index __arg449 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(449));\
t_data_id __arg450 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(450));\
t_array_index __arg451 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(451));\
t_data_id __arg452 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(452));\
t_array_index __arg453 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(453));\
t_data_id __arg454 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(454));\
t_array_index __arg455 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(455));\
t_data_id __arg456 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(456));\
t_array_index __arg457 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(457));\
t_data_id __arg458 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(458));\
t_array_index __arg459 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(459));\
t_data_id __arg460 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(460));\
t_array_index __arg461 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(461));\
t_data_id __arg462 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(462));\
t_array_index __arg463 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(463));\
t_data_id __arg464 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(464));\
t_array_index __arg465 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(465));\
t_data_id __arg466 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(466));\
t_array_index __arg467 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(467));\
t_data_id __arg468 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(468));\
t_array_index __arg469 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(469));\
t_data_id __arg470 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(470));\
t_array_index __arg471 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(471));\
t_data_id __arg472 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(472));\
t_array_index __arg473 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(473));\
t_data_id __arg474 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(474));\
t_array_index __arg475 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(475));\
t_data_id __arg476 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(476));\
t_array_index __arg477 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(477));\
t_data_id __arg478 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(478));\
t_array_index __arg479 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(479));\
t_data_state_db __arg480 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(480));\
t_data_state_db __arg481 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(481));\
t_data_state_db __arg482 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(482));\
t_data_state_db __arg483 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(483));\
t_data_state_db __arg484 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(484));\
t_data_state_db __arg485 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(485));\
t_data_state_db __arg486 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(486));\
t_data_state_db __arg487 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(487));\
t_data_check_Common __arg488 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(488));\
t_time_msec_Common __arg489 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(489));\
t_distance_Common __arg490 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(490));\
Q_UPDOWN_ERTMS_Types __arg491 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(491));\
kcg_uint32 __arg492 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(492));\
kcg_uint32 __arg493 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(493));\
Q_MEDIA_ERTMS_Types __arg494 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(494));\
N_PIG_ERTMS_Types __arg495 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(495));\
N_TOTAL_ERTMS_Types __arg496 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(496));\
M_DUP_ERTMS_Types __arg497 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(497));\
M_MCOUNT_ERTMS_Types __arg498 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(498));\
NID_C_ERTMS_Types __arg499 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(499));\
NID_BG_ERTMS_Types __arg500 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(500));\
Q_LINK_ERTMS_Types __arg501 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(501));\
t_data_check_Common __arg502 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(502));\
t_time_msec_Common __arg503 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(503));\
t_distance_Common __arg504 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(504));\
Q_UPDOWN_ERTMS_Types __arg505 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(505));\
kcg_uint32 __arg506 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(506));\
kcg_uint32 __arg507 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(507));\
Q_MEDIA_ERTMS_Types __arg508 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(508));\
N_PIG_ERTMS_Types __arg509 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(509));\
N_TOTAL_ERTMS_Types __arg510 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(510));\
M_DUP_ERTMS_Types __arg511 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(511));\
M_MCOUNT_ERTMS_Types __arg512 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(512));\
NID_C_ERTMS_Types __arg513 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(513));\
NID_BG_ERTMS_Types __arg514 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(514));\
Q_LINK_ERTMS_Types __arg515 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(515));\
t_data_check_Common __arg516 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(516));\
t_time_msec_Common __arg517 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(517));\
t_distance_Common __arg518 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(518));\
Q_UPDOWN_ERTMS_Types __arg519 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(519));\
kcg_uint32 __arg520 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(520));\
kcg_uint32 __arg521 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(521));\
Q_MEDIA_ERTMS_Types __arg522 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(522));\
N_PIG_ERTMS_Types __arg523 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(523));\
N_TOTAL_ERTMS_Types __arg524 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(524));\
M_DUP_ERTMS_Types __arg525 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(525));\
M_MCOUNT_ERTMS_Types __arg526 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(526));\
NID_C_ERTMS_Types __arg527 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(527));\
NID_BG_ERTMS_Types __arg528 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(528));\
Q_LINK_ERTMS_Types __arg529 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(529));\
t_data_check_Common __arg530 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(530));\
t_time_msec_Common __arg531 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(531));\
t_distance_Common __arg532 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(532));\
Q_UPDOWN_ERTMS_Types __arg533 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(533));\
kcg_uint32 __arg534 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(534));\
kcg_uint32 __arg535 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(535));\
Q_MEDIA_ERTMS_Types __arg536 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(536));\
N_PIG_ERTMS_Types __arg537 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(537));\
N_TOTAL_ERTMS_Types __arg538 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(538));\
M_DUP_ERTMS_Types __arg539 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(539));\
M_MCOUNT_ERTMS_Types __arg540 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(540));\
NID_C_ERTMS_Types __arg541 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(541));\
NID_BG_ERTMS_Types __arg542 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(542));\
Q_LINK_ERTMS_Types __arg543 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(543));\
t_data_check_Common __arg544 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(544));\
t_time_msec_Common __arg545 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(545));\
t_distance_Common __arg546 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(546));\
Q_UPDOWN_ERTMS_Types __arg547 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(547));\
kcg_uint32 __arg548 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(548));\
kcg_uint32 __arg549 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(549));\
Q_MEDIA_ERTMS_Types __arg550 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(550));\
N_PIG_ERTMS_Types __arg551 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(551));\
N_TOTAL_ERTMS_Types __arg552 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(552));\
M_DUP_ERTMS_Types __arg553 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(553));\
M_MCOUNT_ERTMS_Types __arg554 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(554));\
NID_C_ERTMS_Types __arg555 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(555));\
NID_BG_ERTMS_Types __arg556 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(556));\
Q_LINK_ERTMS_Types __arg557 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(557));\
t_data_check_Common __arg558 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(558));\
t_time_msec_Common __arg559 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(559));\
t_distance_Common __arg560 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(560));\
Q_UPDOWN_ERTMS_Types __arg561 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(561));\
kcg_uint32 __arg562 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(562));\
kcg_uint32 __arg563 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(563));\
Q_MEDIA_ERTMS_Types __arg564 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(564));\
N_PIG_ERTMS_Types __arg565 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(565));\
N_TOTAL_ERTMS_Types __arg566 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(566));\
M_DUP_ERTMS_Types __arg567 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(567));\
M_MCOUNT_ERTMS_Types __arg568 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(568));\
NID_C_ERTMS_Types __arg569 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(569));\
NID_BG_ERTMS_Types __arg570 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(570));\
Q_LINK_ERTMS_Types __arg571 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(571));\
t_data_check_Common __arg572 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(572));\
t_time_msec_Common __arg573 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(573));\
t_distance_Common __arg574 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(574));\
Q_UPDOWN_ERTMS_Types __arg575 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(575));\
kcg_uint32 __arg576 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(576));\
kcg_uint32 __arg577 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(577));\
Q_MEDIA_ERTMS_Types __arg578 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(578));\
N_PIG_ERTMS_Types __arg579 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(579));\
N_TOTAL_ERTMS_Types __arg580 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(580));\
M_DUP_ERTMS_Types __arg581 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(581));\
M_MCOUNT_ERTMS_Types __arg582 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(582));\
NID_C_ERTMS_Types __arg583 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(583));\
NID_BG_ERTMS_Types __arg584 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(584));\
Q_LINK_ERTMS_Types __arg585 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(585));\
t_data_check_Common __arg586 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(586));\
t_time_msec_Common __arg587 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(587));\
t_distance_Common __arg588 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(588));\
Q_UPDOWN_ERTMS_Types __arg589 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(589));\
kcg_uint32 __arg590 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(590));\
kcg_uint32 __arg591 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(591));\
Q_MEDIA_ERTMS_Types __arg592 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(592));\
N_PIG_ERTMS_Types __arg593 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(593));\
N_TOTAL_ERTMS_Types __arg594 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(594));\
M_DUP_ERTMS_Types __arg595 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(595));\
M_MCOUNT_ERTMS_Types __arg596 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(596));\
NID_C_ERTMS_Types __arg597 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(597));\
NID_BG_ERTMS_Types __arg598 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(598));\
Q_LINK_ERTMS_Types __arg599 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(599));\
t_data_state_db __arg600 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(600));\
t_status_comm_session_Common __arg601 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(601));\
t_data_state_db __arg602 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(602));\
N_ITER_ERTMS_Types __arg603 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(603));\
t_data_state_db __arg604 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(604));\
e_FUNCTION_STATE_FunctionsRelated __arg605 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(605));\
e_FUNCTION_STATE_FunctionsRelated __arg606 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(606));\
e_FUNCTION_STATE_FunctionsRelated __arg607 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(607));\
e_FUNCTION_STATE_FunctionsRelated __arg608 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(608));\
e_FUNCTION_STATE_FunctionsRelated __arg609 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(609));\
e_FUNCTION_STATE_FunctionsRelated __arg610 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(610));\
e_FUNCTION_STATE_FunctionsRelated __arg611 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(611));\
e_FUNCTION_STATE_FunctionsRelated __arg612 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(612));\
e_FUNCTION_STATE_FunctionsRelated __arg613 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(613));\
e_FUNCTION_STATE_FunctionsRelated __arg614 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(614));\
e_FUNCTION_STATE_FunctionsRelated __arg615 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(615));\
e_FUNCTION_STATE_FunctionsRelated __arg616 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(616));\
e_FUNCTION_STATE_FunctionsRelated __arg617 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(617));\
e_FUNCTION_STATE_FunctionsRelated __arg618 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(618));\
e_FUNCTION_STATE_FunctionsRelated __arg619 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(619));\
e_FUNCTION_STATE_FunctionsRelated __arg620 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(620));\
e_FUNCTION_STATE_FunctionsRelated __arg621 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(621));\
e_FUNCTION_STATE_FunctionsRelated __arg622 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(622));\
e_FUNCTION_STATE_FunctionsRelated __arg623 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(623));\
e_FUNCTION_STATE_FunctionsRelated __arg624 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(624));\
e_FUNCTION_STATE_FunctionsRelated __arg625 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(625));\
e_FUNCTION_STATE_FunctionsRelated __arg626 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(626));\
e_FUNCTION_STATE_FunctionsRelated __arg627 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(627));\
e_FUNCTION_STATE_FunctionsRelated __arg628 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(628));\
e_FUNCTION_STATE_FunctionsRelated __arg629 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(629));\
e_FUNCTION_STATE_FunctionsRelated __arg630 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(630));\
e_FUNCTION_STATE_FunctionsRelated __arg631 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(631));\
e_FUNCTION_STATE_FunctionsRelated __arg632 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(632));\
e_FUNCTION_STATE_FunctionsRelated __arg633 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(633));\
e_FUNCTION_STATE_FunctionsRelated __arg634 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(634));\
e_FUNCTION_STATE_FunctionsRelated __arg635 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(635));\
e_FUNCTION_STATE_FunctionsRelated __arg636 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(636));\
e_FUNCTION_STATE_FunctionsRelated __arg637 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(637));\
e_FUNCTION_STATE_FunctionsRelated __arg638 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(638));\
e_FUNCTION_STATE_FunctionsRelated __arg639 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(639));\
e_FUNCTION_STATE_FunctionsRelated __arg640 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(640));\
e_FUNCTION_STATE_FunctionsRelated __arg641 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(641));\
e_FUNCTION_STATE_FunctionsRelated __arg642 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(642));\
e_FUNCTION_STATE_FunctionsRelated __arg643 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(643));\
e_FUNCTION_STATE_FunctionsRelated __arg644 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(644));\
e_FUNCTION_STATE_FunctionsRelated __arg645 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(645));\
e_FUNCTION_STATE_FunctionsRelated __arg646 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(646));\
e_FUNCTION_STATE_FunctionsRelated __arg647 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(647));\
e_FUNCTION_STATE_FunctionsRelated __arg648 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(648));\
e_FUNCTION_STATE_FunctionsRelated __arg649 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(649));\
e_FUNCTION_STATE_FunctionsRelated __arg650 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(650));\
e_FUNCTION_STATE_FunctionsRelated __arg651 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(651));\
e_FUNCTION_STATE_FunctionsRelated __arg652 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(652));\
e_FUNCTION_STATE_FunctionsRelated __arg653 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(653));\
e_FUNCTION_STATE_FunctionsRelated __arg654 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(654));\
e_FUNCTION_STATE_FunctionsRelated __arg655 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(655));\
e_FUNCTION_STATE_FunctionsRelated __arg656 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(656));\
e_FUNCTION_STATE_FunctionsRelated __arg657 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(657));\
e_FUNCTION_STATE_FunctionsRelated __arg658 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(658));\
e_FUNCTION_STATE_FunctionsRelated __arg659 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(659));\
e_FUNCTION_STATE_FunctionsRelated __arg660 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(660));\
e_FUNCTION_STATE_FunctionsRelated __arg661 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(661));\
e_FUNCTION_STATE_FunctionsRelated __arg662 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(662));\
e_FUNCTION_STATE_FunctionsRelated __arg663 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(663));\
e_FUNCTION_STATE_FunctionsRelated __arg664 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(664));\
e_FUNCTION_STATE_FunctionsRelated __arg665 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(665));\
e_FUNCTION_STATE_FunctionsRelated __arg666 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(666));\
e_FUNCTION_STATE_FunctionsRelated __arg667 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(667));\
e_FUNCTION_STATE_FunctionsRelated __arg668 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(668));\
e_FUNCTION_STATE_FunctionsRelated __arg669 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(669));\
e_FUNCTION_STATE_FunctionsRelated __arg670 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(670));\
e_FUNCTION_STATE_FunctionsRelated __arg671 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(671));\
e_FUNCTION_STATE_FunctionsRelated __arg672 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(672));\
e_FUNCTION_STATE_FunctionsRelated __arg673 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(673));\
e_FUNCTION_STATE_FunctionsRelated __arg674 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(674));\
e_FUNCTION_STATE_FunctionsRelated __arg675 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(675));\
e_FUNCTION_STATE_FunctionsRelated __arg676 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(676));\
e_FUNCTION_STATE_FunctionsRelated __arg677 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(677));\
e_FUNCTION_STATE_FunctionsRelated __arg678 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(678));\
e_FUNCTION_STATE_FunctionsRelated __arg679 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(679));\
e_FUNCTION_STATE_FunctionsRelated __arg680 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(680));\
e_FUNCTION_STATE_FunctionsRelated __arg681 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(681));\
t_data_state_db __arg682 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(682));\
M_LEVEL_ERTMS_Types __arg683 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(683));\
NID_NTC_ERTMS_Types __arg684 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(684));\
t_data_state_db __arg685 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(685));\
MinSafeAntennaPosition_FunctionsRelated __arg686 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(686));\
t_data_state_db __arg687 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(687));\
t_orientation_Common __arg688 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(688));\
t_data_state_db __arg689 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(689));\
kcg_bool __arg690 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(690));\
t_data_state_db __arg691 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(691));\
kcg_int32 __arg692 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(692));\
kcg_int32 __arg693 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(693));\
kcg_int32 __arg694 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(694));\
kcg_int32 __arg695 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(695));\
kcg_int32 __arg696 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(696));\
kcg_int32 __arg697 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(697));\
Q_DLRBG_ERTMS_Types __arg698 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(698));\
Q_DIRLRBG_ERTMS_Types __arg699 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(699));\
Q_DIRTRAIN_ERTMS_Types __arg700 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(700));\
t_data_state_db __arg701 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(701));\
N_ITER_ERTMS_Types __arg702 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(702));\
kcg_int32 __arg703 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(703));\
Q_NEWCOUNTRY_ERTMS_Types __arg704 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(704));\
kcg_uint16 __arg705 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(705));\
kcg_uint16 __arg706 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(706));\
Q_LINKORIENTATION_ERTMS_Types __arg707 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(707));\
Q_LINKREACTION_ERTMS_Types __arg708 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(708));\
kcg_int32 __arg709 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(709));\
kcg_int32 __arg710 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(710));\
Q_NEWCOUNTRY_ERTMS_Types __arg711 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(711));\
kcg_uint16 __arg712 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(712));\
kcg_uint16 __arg713 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(713));\
Q_LINKORIENTATION_ERTMS_Types __arg714 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(714));\
Q_LINKREACTION_ERTMS_Types __arg715 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(715));\
kcg_int32 __arg716 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(716));\
kcg_int32 __arg717 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(717));\
Q_NEWCOUNTRY_ERTMS_Types __arg718 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(718));\
kcg_uint16 __arg719 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(719));\
kcg_uint16 __arg720 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(720));\
Q_LINKORIENTATION_ERTMS_Types __arg721 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(721));\
Q_LINKREACTION_ERTMS_Types __arg722 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(722));\
kcg_int32 __arg723 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(723));\
kcg_int32 __arg724 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(724));\
Q_NEWCOUNTRY_ERTMS_Types __arg725 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(725));\
kcg_uint16 __arg726 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(726));\
kcg_uint16 __arg727 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(727));\
Q_LINKORIENTATION_ERTMS_Types __arg728 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(728));\
Q_LINKREACTION_ERTMS_Types __arg729 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(729));\
kcg_int32 __arg730 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(730));\
kcg_int32 __arg731 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(731));\
Q_NEWCOUNTRY_ERTMS_Types __arg732 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(732));\
kcg_uint16 __arg733 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(733));\
kcg_uint16 __arg734 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(734));\
Q_LINKORIENTATION_ERTMS_Types __arg735 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(735));\
Q_LINKREACTION_ERTMS_Types __arg736 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(736));\
kcg_int32 __arg737 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(737));\
kcg_int32 __arg738 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(738));\
Q_NEWCOUNTRY_ERTMS_Types __arg739 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(739));\
kcg_uint16 __arg740 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(740));\
kcg_uint16 __arg741 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(741));\
Q_LINKORIENTATION_ERTMS_Types __arg742 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(742));\
Q_LINKREACTION_ERTMS_Types __arg743 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(743));\
kcg_int32 __arg744 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(744));\
kcg_int32 __arg745 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(745));\
Q_NEWCOUNTRY_ERTMS_Types __arg746 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(746));\
kcg_uint16 __arg747 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(747));\
kcg_uint16 __arg748 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(748));\
Q_LINKORIENTATION_ERTMS_Types __arg749 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(749));\
Q_LINKREACTION_ERTMS_Types __arg750 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(750));\
kcg_int32 __arg751 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(751));\
kcg_int32 __arg752 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(752));\
Q_NEWCOUNTRY_ERTMS_Types __arg753 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(753));\
kcg_uint16 __arg754 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(754));\
kcg_uint16 __arg755 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(755));\
Q_LINKORIENTATION_ERTMS_Types __arg756 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(756));\
Q_LINKREACTION_ERTMS_Types __arg757 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(757));\
kcg_int32 __arg758 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(758));\
kcg_int32 __arg759 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(759));\
Q_NEWCOUNTRY_ERTMS_Types __arg760 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(760));\
kcg_uint16 __arg761 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(761));\
kcg_uint16 __arg762 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(762));\
Q_LINKORIENTATION_ERTMS_Types __arg763 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(763));\
Q_LINKREACTION_ERTMS_Types __arg764 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(764));\
kcg_int32 __arg765 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(765));\
kcg_int32 __arg766 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(766));\
Q_NEWCOUNTRY_ERTMS_Types __arg767 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(767));\
kcg_uint16 __arg768 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(768));\
kcg_uint16 __arg769 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(769));\
Q_LINKORIENTATION_ERTMS_Types __arg770 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(770));\
Q_LINKREACTION_ERTMS_Types __arg771 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(771));\
kcg_int32 __arg772 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(772));\
kcg_int32 __arg773 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(773));\
Q_NEWCOUNTRY_ERTMS_Types __arg774 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(774));\
kcg_uint16 __arg775 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(775));\
kcg_uint16 __arg776 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(776));\
Q_LINKORIENTATION_ERTMS_Types __arg777 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(777));\
Q_LINKREACTION_ERTMS_Types __arg778 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(778));\
kcg_int32 __arg779 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(779));\
kcg_int32 __arg780 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(780));\
Q_NEWCOUNTRY_ERTMS_Types __arg781 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(781));\
kcg_uint16 __arg782 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(782));\
kcg_uint16 __arg783 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(783));\
Q_LINKORIENTATION_ERTMS_Types __arg784 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(784));\
Q_LINKREACTION_ERTMS_Types __arg785 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(785));\
kcg_int32 __arg786 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(786));\
kcg_int32 __arg787 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(787));\
Q_NEWCOUNTRY_ERTMS_Types __arg788 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(788));\
kcg_uint16 __arg789 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(789));\
kcg_uint16 __arg790 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(790));\
Q_LINKORIENTATION_ERTMS_Types __arg791 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(791));\
Q_LINKREACTION_ERTMS_Types __arg792 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(792));\
kcg_int32 __arg793 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(793));\
kcg_int32 __arg794 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(794));\
Q_NEWCOUNTRY_ERTMS_Types __arg795 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(795));\
kcg_uint16 __arg796 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(796));\
kcg_uint16 __arg797 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(797));\
Q_LINKORIENTATION_ERTMS_Types __arg798 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(798));\
Q_LINKREACTION_ERTMS_Types __arg799 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(799));\
kcg_int32 __arg800 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(800));\
kcg_int32 __arg801 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(801));\
Q_NEWCOUNTRY_ERTMS_Types __arg802 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(802));\
kcg_uint16 __arg803 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(803));\
kcg_uint16 __arg804 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(804));\
Q_LINKORIENTATION_ERTMS_Types __arg805 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(805));\
Q_LINKREACTION_ERTMS_Types __arg806 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(806));\
kcg_int32 __arg807 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(807));\
kcg_int32 __arg808 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(808));\
Q_NEWCOUNTRY_ERTMS_Types __arg809 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(809));\
kcg_uint16 __arg810 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(810));\
kcg_uint16 __arg811 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(811));\
Q_LINKORIENTATION_ERTMS_Types __arg812 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(812));\
Q_LINKREACTION_ERTMS_Types __arg813 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(813));\
kcg_int32 __arg814 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(814));\
kcg_int32 __arg815 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(815));\
Q_NEWCOUNTRY_ERTMS_Types __arg816 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(816));\
kcg_uint16 __arg817 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(817));\
kcg_uint16 __arg818 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(818));\
Q_LINKORIENTATION_ERTMS_Types __arg819 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(819));\
Q_LINKREACTION_ERTMS_Types __arg820 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(820));\
kcg_int32 __arg821 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(821));\
kcg_int32 __arg822 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(822));\
Q_NEWCOUNTRY_ERTMS_Types __arg823 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(823));\
kcg_uint16 __arg824 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(824));\
kcg_uint16 __arg825 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(825));\
Q_LINKORIENTATION_ERTMS_Types __arg826 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(826));\
Q_LINKREACTION_ERTMS_Types __arg827 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(827));\
kcg_int32 __arg828 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(828));\
kcg_int32 __arg829 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(829));\
Q_NEWCOUNTRY_ERTMS_Types __arg830 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(830));\
kcg_uint16 __arg831 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(831));\
kcg_uint16 __arg832 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(832));\
Q_LINKORIENTATION_ERTMS_Types __arg833 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(833));\
Q_LINKREACTION_ERTMS_Types __arg834 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(834));\
kcg_int32 __arg835 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(835));\
kcg_int32 __arg836 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(836));\
Q_NEWCOUNTRY_ERTMS_Types __arg837 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(837));\
kcg_uint16 __arg838 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(838));\
kcg_uint16 __arg839 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(839));\
Q_LINKORIENTATION_ERTMS_Types __arg840 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(840));\
Q_LINKREACTION_ERTMS_Types __arg841 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(841));\
kcg_int32 __arg842 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(842));\
kcg_int32 __arg843 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(843));\
Q_NEWCOUNTRY_ERTMS_Types __arg844 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(844));\
kcg_uint16 __arg845 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(845));\
kcg_uint16 __arg846 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(846));\
Q_LINKORIENTATION_ERTMS_Types __arg847 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(847));\
Q_LINKREACTION_ERTMS_Types __arg848 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(848));\
kcg_int32 __arg849 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(849));\
kcg_int32 __arg850 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(850));\
Q_NEWCOUNTRY_ERTMS_Types __arg851 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(851));\
kcg_uint16 __arg852 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(852));\
kcg_uint16 __arg853 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(853));\
Q_LINKORIENTATION_ERTMS_Types __arg854 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(854));\
Q_LINKREACTION_ERTMS_Types __arg855 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(855));\
kcg_int32 __arg856 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(856));\
kcg_int32 __arg857 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(857));\
Q_NEWCOUNTRY_ERTMS_Types __arg858 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(858));\
kcg_uint16 __arg859 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(859));\
kcg_uint16 __arg860 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(860));\
Q_LINKORIENTATION_ERTMS_Types __arg861 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(861));\
Q_LINKREACTION_ERTMS_Types __arg862 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(862));\
kcg_int32 __arg863 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(863));\
kcg_int32 __arg864 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(864));\
Q_NEWCOUNTRY_ERTMS_Types __arg865 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(865));\
kcg_uint16 __arg866 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(866));\
kcg_uint16 __arg867 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(867));\
Q_LINKORIENTATION_ERTMS_Types __arg868 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(868));\
Q_LINKREACTION_ERTMS_Types __arg869 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(869));\
kcg_int32 __arg870 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(870));\
kcg_int32 __arg871 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(871));\
Q_NEWCOUNTRY_ERTMS_Types __arg872 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(872));\
kcg_uint16 __arg873 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(873));\
kcg_uint16 __arg874 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(874));\
Q_LINKORIENTATION_ERTMS_Types __arg875 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(875));\
Q_LINKREACTION_ERTMS_Types __arg876 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(876));\
kcg_int32 __arg877 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(877));\
kcg_int32 __arg878 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(878));\
Q_NEWCOUNTRY_ERTMS_Types __arg879 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(879));\
kcg_uint16 __arg880 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(880));\
kcg_uint16 __arg881 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(881));\
Q_LINKORIENTATION_ERTMS_Types __arg882 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(882));\
Q_LINKREACTION_ERTMS_Types __arg883 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(883));\
kcg_int32 __arg884 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(884));\
kcg_int32 __arg885 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(885));\
Q_NEWCOUNTRY_ERTMS_Types __arg886 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(886));\
kcg_uint16 __arg887 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(887));\
kcg_uint16 __arg888 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(888));\
Q_LINKORIENTATION_ERTMS_Types __arg889 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(889));\
Q_LINKREACTION_ERTMS_Types __arg890 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(890));\
kcg_int32 __arg891 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(891));\
kcg_int32 __arg892 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(892));\
Q_NEWCOUNTRY_ERTMS_Types __arg893 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(893));\
kcg_uint16 __arg894 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(894));\
kcg_uint16 __arg895 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(895));\
Q_LINKORIENTATION_ERTMS_Types __arg896 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(896));\
Q_LINKREACTION_ERTMS_Types __arg897 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(897));\
kcg_int32 __arg898 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(898));\
kcg_int32 __arg899 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(899));\
Q_NEWCOUNTRY_ERTMS_Types __arg900 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(900));\
kcg_uint16 __arg901 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(901));\
kcg_uint16 __arg902 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(902));\
Q_LINKORIENTATION_ERTMS_Types __arg903 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(903));\
Q_LINKREACTION_ERTMS_Types __arg904 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(904));\
kcg_int32 __arg905 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(905));\
kcg_int32 __arg906 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(906));\
Q_NEWCOUNTRY_ERTMS_Types __arg907 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(907));\
kcg_uint16 __arg908 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(908));\
kcg_uint16 __arg909 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(909));\
Q_LINKORIENTATION_ERTMS_Types __arg910 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(910));\
Q_LINKREACTION_ERTMS_Types __arg911 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(911));\
kcg_int32 __arg912 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(912));\
t_data_state_db __arg913 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(913));\
kcg_bool __arg914 = OCELOT_NUM(OCELOT_ARGUMENT_VALUE(914));\
OCELOT_TESTFUNCTION (__arg0,__arg1,__arg2,__arg3,__arg4,__arg5,__arg6,__arg7,__arg8,__arg9,__arg10,__arg11,__arg12,__arg13,__arg14,__arg15,__arg16,__arg17,__arg18,__arg19,__arg20,__arg21,__arg22,__arg23,__arg24,__arg25,__arg26,__arg27,__arg28,__arg29,__arg30,__arg31,__arg32,__arg33,__arg34,__arg35,__arg36,__arg37,__arg38,__arg39,__arg40,__arg41,__arg42,__arg43,__arg44,__arg45,__arg46,__arg47,__arg48,__arg49,__arg50,__arg51,__arg52,__arg53,__arg54,__arg55,__arg56,__arg57,__arg58,__arg59,__arg60,__arg61,__arg62,__arg63,__arg64,__arg65,__arg66,__arg67,__arg68,__arg69,__arg70,__arg71,__arg72,__arg73,__arg74,__arg75,__arg76,__arg77,__arg78,__arg79,__arg80,__arg81,__arg82,__arg83,__arg84,__arg85,__arg86,__arg87,__arg88,__arg89,__arg90,__arg91,__arg92,__arg93,__arg94,__arg95,__arg96,__arg97,__arg98,__arg99,__arg100,__arg101,__arg102,__arg103,__arg104,__arg105,__arg106,__arg107,__arg108,__arg109,__arg110,__arg111,__arg112,__arg113,__arg114,__arg115,__arg116,__arg117,__arg118,__arg119,__arg120,__arg121,__arg122,__arg123,__arg124,__arg125,__arg126,__arg127,__arg128,__arg129,__arg130,__arg131,__arg132,__arg133,__arg134,__arg135,__arg136,__arg137,__arg138,__arg139,__arg140,__arg141,__arg142,__arg143,__arg144,__arg145,__arg146,__arg147,__arg148,__arg149,__arg150,__arg151,__arg152,__arg153,__arg154,__arg155,__arg156,__arg157,__arg158,__arg159,__arg160,__arg161,__arg162,__arg163,__arg164,__arg165,__arg166,__arg167,__arg168,__arg169,__arg170,__arg171,__arg172,__arg173,__arg174,__arg175,__arg176,__arg177,__arg178,__arg179,__arg180,__arg181,__arg182,__arg183,__arg184,__arg185,__arg186,__arg187,__arg188,__arg189,__arg190,__arg191,__arg192,__arg193,__arg194,__arg195,__arg196,__arg197,__arg198,__arg199,__arg200,__arg201,__arg202,__arg203,__arg204,__arg205,__arg206,__arg207,__arg208,__arg209,__arg210,__arg211,__arg212,__arg213,__arg214,__arg215,__arg216,__arg217,__arg218,__arg219,__arg220,__arg221,__arg222,__arg223,__arg224,__arg225,__arg226,__arg227,__arg228,__arg229,__arg230,__arg231,__arg232,__arg233,__arg234,__arg235,__arg236,__arg237,__arg238,__arg239,__arg240,__arg241,__arg242,__arg243,__arg244,__arg245,__arg246,__arg247,__arg248,__arg249,__arg250,__arg251,__arg252,__arg253,__arg254,__arg255,__arg256,__arg257,__arg258,__arg259,__arg260,__arg261,__arg262,__arg263,__arg264,__arg265,__arg266,__arg267,__arg268,__arg269,__arg270,__arg271,__arg272,__arg273,__arg274,__arg275,__arg276,__arg277,__arg278,__arg279,__arg280,__arg281,__arg282,__arg283,__arg284,__arg285,__arg286,__arg287,__arg288,__arg289,__arg290,__arg291,__arg292,__arg293,__arg294,__arg295,__arg296,__arg297,__arg298,__arg299,__arg300,__arg301,__arg302,__arg303,__arg304,__arg305,__arg306,__arg307,__arg308,__arg309,__arg310,__arg311,__arg312,__arg313,__arg314,__arg315,__arg316,__arg317,__arg318,__arg319,__arg320,__arg321,__arg322,__arg323,__arg324,__arg325,__arg326,__arg327,__arg328,__arg329,__arg330,__arg331,__arg332,__arg333,__arg334,__arg335,__arg336,__arg337,__arg338,__arg339,__arg340,__arg341,__arg342,__arg343,__arg344,__arg345,__arg346,__arg347,__arg348,__arg349,__arg350,__arg351,__arg352,__arg353,__arg354,__arg355,__arg356,__arg357,__arg358,__arg359,__arg360,__arg361,__arg362,__arg363,__arg364,__arg365,__arg366,__arg367,__arg368,__arg369,__arg370,__arg371,__arg372,__arg373,__arg374,__arg375,__arg376,__arg377,__arg378,__arg379,__arg380,__arg381,__arg382,__arg383,__arg384,__arg385,__arg386,__arg387,__arg388,__arg389,__arg390,__arg391,__arg392,__arg393,__arg394,__arg395,__arg396,__arg397,__arg398,__arg399,__arg400,__arg401,__arg402,__arg403,__arg404,__arg405,__arg406,__arg407,__arg408,__arg409,__arg410,__arg411,__arg412,__arg413,__arg414,__arg415,__arg416,__arg417,__arg418,__arg419,__arg420,__arg421,__arg422,__arg423,__arg424,__arg425,__arg426,__arg427,__arg428,__arg429,__arg430,__arg431,__arg432,__arg433,__arg434,__arg435,__arg436,__arg437,__arg438,__arg439,__arg440,__arg441,__arg442,__arg443,__arg444,__arg445,__arg446,__arg447,__arg448,__arg449,__arg450,__arg451,__arg452,__arg453,__arg454,__arg455,__arg456,__arg457,__arg458,__arg459,__arg460,__arg461,__arg462,__arg463,__arg464,__arg465,__arg466,__arg467,__arg468,__arg469,__arg470,__arg471,__arg472,__arg473,__arg474,__arg475,__arg476,__arg477,__arg478,__arg479,__arg480,__arg481,__arg482,__arg483,__arg484,__arg485,__arg486,__arg487,__arg488,__arg489,__arg490,__arg491,__arg492,__arg493,__arg494,__arg495,__arg496,__arg497,__arg498,__arg499,__arg500,__arg501,__arg502,__arg503,__arg504,__arg505,__arg506,__arg507,__arg508,__arg509,__arg510,__arg511,__arg512,__arg513,__arg514,__arg515,__arg516,__arg517,__arg518,__arg519,__arg520,__arg521,__arg522,__arg523,__arg524,__arg525,__arg526,__arg527,__arg528,__arg529,__arg530,__arg531,__arg532,__arg533,__arg534,__arg535,__arg536,__arg537,__arg538,__arg539,__arg540,__arg541,__arg542,__arg543,__arg544,__arg545,__arg546,__arg547,__arg548,__arg549,__arg550,__arg551,__arg552,__arg553,__arg554,__arg555,__arg556,__arg557,__arg558,__arg559,__arg560,__arg561,__arg562,__arg563,__arg564,__arg565,__arg566,__arg567,__arg568,__arg569,__arg570,__arg571,__arg572,__arg573,__arg574,__arg575,__arg576,__arg577,__arg578,__arg579,__arg580,__arg581,__arg582,__arg583,__arg584,__arg585,__arg586,__arg587,__arg588,__arg589,__arg590,__arg591,__arg592,__arg593,__arg594,__arg595,__arg596,__arg597,__arg598,__arg599,__arg600,__arg601,__arg602,__arg603,__arg604,__arg605,__arg606,__arg607,__arg608,__arg609,__arg610,__arg611,__arg612,__arg613,__arg614,__arg615,__arg616,__arg617,__arg618,__arg619,__arg620,__arg621,__arg622,__arg623,__arg624,__arg625,__arg626,__arg627,__arg628,__arg629,__arg630,__arg631,__arg632,__arg633,__arg634,__arg635,__arg636,__arg637,__arg638,__arg639,__arg640,__arg641,__arg642,__arg643,__arg644,__arg645,__arg646,__arg647,__arg648,__arg649,__arg650,__arg651,__arg652,__arg653,__arg654,__arg655,__arg656,__arg657,__arg658,__arg659,__arg660,__arg661,__arg662,__arg663,__arg664,__arg665,__arg666,__arg667,__arg668,__arg669,__arg670,__arg671,__arg672,__arg673,__arg674,__arg675,__arg676,__arg677,__arg678,__arg679,__arg680,__arg681,__arg682,__arg683,__arg684,__arg685,__arg686,__arg687,__arg688,__arg689,__arg690,__arg691,__arg692,__arg693,__arg694,__arg695,__arg696,__arg697,__arg698,__arg699,__arg700,__arg701,__arg702,__arg703,__arg704,__arg705,__arg706,__arg707,__arg708,__arg709,__arg710,__arg711,__arg712,__arg713,__arg714,__arg715,__arg716,__arg717,__arg718,__arg719,__arg720,__arg721,__arg722,__arg723,__arg724,__arg725,__arg726,__arg727,__arg728,__arg729,__arg730,__arg731,__arg732,__arg733,__arg734,__arg735,__arg736,__arg737,__arg738,__arg739,__arg740,__arg741,__arg742,__arg743,__arg744,__arg745,__arg746,__arg747,__arg748,__arg749,__arg750,__arg751,__arg752,__arg753,__arg754,__arg755,__arg756,__arg757,__arg758,__arg759,__arg760,__arg761,__arg762,__arg763,__arg764,__arg765,__arg766,__arg767,__arg768,__arg769,__arg770,__arg771,__arg772,__arg773,__arg774,__arg775,__arg776,__arg777,__arg778,__arg779,__arg780,__arg781,__arg782,__arg783,__arg784,__arg785,__arg786,__arg787,__arg788,__arg789,__arg790,__arg791,__arg792,__arg793,__arg794,__arg795,__arg796,__arg797,__arg798,__arg799,__arg800,__arg801,__arg802,__arg803,__arg804,__arg805,__arg806,__arg807,__arg808,__arg809,__arg810,__arg811,__arg812,__arg813,__arg814,__arg815,__arg816,__arg817,__arg818,__arg819,__arg820,__arg821,__arg822,__arg823,__arg824,__arg825,__arg826,__arg827,__arg828,__arg829,__arg830,__arg831,__arg832,__arg833,__arg834,__arg835,__arg836,__arg837,__arg838,__arg839,__arg840,__arg841,__arg842,__arg843,__arg844,__arg845,__arg846,__arg847,__arg848,__arg849,__arg850,__arg851,__arg852,__arg853,__arg854,__arg855,__arg856,__arg857,__arg858,__arg859,__arg860,__arg861,__arg862,__arg863,__arg864,__arg865,__arg866,__arg867,__arg868,__arg869,__arg870,__arg871,__arg872,__arg873,__arg874,__arg875,__arg876,__arg877,__arg878,__arg879,__arg880,__arg881,__arg882,__arg883,__arg884,__arg885,__arg886,__arg887,__arg888,__arg889,__arg890,__arg891,__arg892,__arg893,__arg894,__arg895,__arg896,__arg897,__arg898,__arg899,__arg900,__arg901,__arg902,__arg903,__arg904,__arg905,__arg906,__arg907,__arg908,__arg909,__arg910,__arg911,__arg912,__arg913,__arg914);



/*
 * ATTENTION:
 * The Java builder (it.unisa.ocelot.runnable.Build) will enrich this meta-c file with:
 * 1) The import if it_unisa_ocelot_simulator_CBridge.h file
 * 2) The definition of EXECUTE_OCELOT_TEST macro
 * Please, do not consider the absence of this part an error.
 */
#include <stdio.h>
#include <signal.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <sys/ipc.h>
#include <sys/shm.h>
#include <stdlib.h>
#include <sys/mman.h>
#include <fcntl.h>
#include <errno.h>
#include <unistd.h>
#include <semaphore.h>

#define NODEBUGINFO -324354

#define LOCKNAME_C "/tmp/.ocelot_c%d.lock"
#define LOCKNAME_P "/tmp/.ocelot_p%d.lock"
#define LOCKNAME_R "/tmp/.ocelot_r%d.lock"

//#define LOGGER

#ifdef LOGGER
#define LOG_SEPARATOR(logger) fputs("########################\n\n", logger)
#define LOG_EVENT(event, logger) fprintf(logger, "Event:\n");\
						 fprintf(logger, "Choice: %d\n", event.choice);\
						 fprintf(logger, "distanceTrue: %f\n", event.distanceTrue);\
						 fprintf(logger, "distanceFalse: %f\n", event.distanceFalse);\
						 fputs("---------------\n", logger)
#else
#define LOG_SEPARATOR(logger) {}
#define LOG_EVENT(event, logger) {}

#endif
						 
extern _T_ocelot_list *_v_ocelot_events;
extern _T_ocelot_list *_v_ocelot_fcalls;

/*
 * Class:     it_unisa_ocelot_simulator_CBridge
 * Method:    getEvents
 * Signature: (Lit/unisa/ocelot/simulator/EventsHandler;)V
 */

volatile void *shm_return;
volatile void *shm_call;

int shared_return_id;
int shared_call_id;

JNIEnv* jnienv;

int childControl;
int parentControl;
int releaser;

pid_t child_processes;

FILE* loggerParent;
FILE* loggerChild;

JNIEXPORT void JNICALL Java_it_unisa_ocelot_simulator_CBridge_privInit
		(JNIEnv *env, jclass cbridge, jint values, jint arrays, jint pointers) {
	int i;

	_f_ocelot_debug("HEY, YOU CALLED ME", NODEBUGINFO);
#ifdef LOGGER
	loggerParent = fopen("OCELOT_LOGGER_P", "w");
	loggerChild = fopen("OCELOT_LOGGER_C", "w");
	fputs("Logger session started.\n", loggerParent);
	fputs("Logger session started.\n", loggerChild);
#endif
	LOG_SEPARATOR(loggerParent);
	LOG_SEPARATOR(loggerChild);

	child_processes = 0;

	int size_call = sizeof(int) + sizeof(int)*3 + sizeof(double)*(int)values + sizeof(double)*(int)arrays*OCELOT_ARRAYS_SIZE + sizeof(double)*(int)pointers;
	int size_return = sizeof(int) + sizeof(_T_ocelot_event) * MAX_EVENTS_NUMBER;

	int pid = _f_ocelot_alloc_process(env, i, size_call, size_return);
	if (pid < 0) {
		char message[100];
		if (pid == -1)
			sprintf(message, "Unable to allocate memory for process %d. Error: %d", i, errno);
		else if (pid == -2)
			sprintf(message, "Unable to gain locks for process %d. Error: %d", i, errno);
		else
			sprintf(message, "Unable to allocate the process %d. Unknown Error.", i);
		_f_ocelot_throw_runtimeexception(env, message);
		goto fail;
	} else {
		printf("PID: %d\n", pid);
		_f_ocelot_debug("PID: %d", pid);

		child_processes = pid;
		_f_ocelot_debug("PARENT: Locked child %d", i);
		LOCK_CHILD();
	}

	return;

fail:
	if (child_processes != 0) {
		kill(child_processes, SIGKILL);
	}
	return;
}

int _f_ocelot_alloc_process(JNIEnv* env, int coreId, int size_call, int size_return) {
	int good;
	int tries = 100;

	do {
		tries--;
		good = 1;

		key_t return_id = (int)(rand()*9999);
		key_t call_id = return_id + 1;

		/*
		 * Create the segment.
		 */
		shared_return_id = shmget(return_id, size_return, IPC_CREAT|IPC_EXCL|0666);
		if (shared_return_id < 0) {
			good = 0;
			continue;
		}

		shared_call_id = shmget(call_id, size_call, IPC_CREAT|IPC_EXCL|0666);
		if (shared_call_id < 0) {
			good = 0;
			shmctl(shared_return_id, IPC_RMID, NULL);
			continue;
		}

	} while (!good && tries > 0);

	if (!good){
		return -1;
	}

	char nameC[50];
	char nameP[50];
	char nameR[50];

	sprintf(nameC, LOCKNAME_C,coreId);
	sprintf(nameP, LOCKNAME_P,coreId);
	sprintf(nameR, LOCKNAME_R,coreId);

	FILE* fileCC = fopen (nameC, "w");
	FILE* filePC = fopen (nameP, "w");
	FILE* fileRC = fopen (nameR, "w");

	childControl = fileno(fileCC);
	parentControl = fileno(filePC);
	releaser = fileno(fileRC);

	if (childControl < 0 || parentControl < 0 || releaser < 0) {
		fclose(fileCC);
		fclose(filePC);
		fclose(fileRC);
		return -2;
	}

	return _f_ocelot_fork(env, coreId);
}

JNIEXPORT void JNICALL Java_it_unisa_ocelot_simulator_CBridge_memoryDump(JNIEnv *env, jobject self) {
	jclass cbridge = (*env)->GetObjectClass(env, self);

	jfieldID coreIdField = (*env)->GetFieldID(env, cbridge, "coreId", "I");
	jint coreId = (*env)->GetIntField(env, self, coreIdField);

	int i;
	shm_call = shmat(shared_call_id, 0, 0);
	shm_return = shmat(shared_return_id, 0, SHM_RDONLY);

	volatile _T_ocelot_call_memory call_memory = _f_ocelot_shared_call(shm_call);
	volatile _T_ocelot_return_memory return_memory = _f_ocelot_shared_return(shm_return);

	fprintf(stderr, "------------ START MEMORY DUMP ------------\n");
	fprintf(stderr, "*** CALL MEMORY ***\n");
	fprintf(stderr, "SIGNAL: %d\n", MEMGET(call_memory.signal));
	fprintf(stderr, "VALUES: %d\n", MEMGET(call_memory.values));
	fprintf(stderr, "ARRAYS: %d\n", MEMGET(call_memory.arrays));
	fprintf(stderr, "POINTERS: %d\n", MEMGET(call_memory.pointers));
	fprintf(stderr, "DATA:\n");
	char* data = (char*)call_memory.data;
	for (i = 0; i < (MEMGET(call_memory.values))+(MEMGET(call_memory.arrays))*OCELOT_ARRAYS_SIZE+(MEMGET(call_memory.pointers));i++) {
		fprintf(stderr, "%d ", *(data+i));
	}

	fprintf(stderr, "\n\n");

	fprintf(stderr, "*** RETURN MEMORY ***\n");
	fprintf(stderr, "SIZE: %d\n", MEMGET(return_memory.size));

	data = (char*)return_memory.events;
	for (i = 0; i < (MEMGET(return_memory.size))*sizeof(_T_ocelot_event); i++) {
		fprintf(stderr, "%d ", *(data+i));
	}
	fprintf(stderr, "\n\n");
	fprintf(stderr, "------------  END MEMORY DUMP  ------------\n");

close:
	shmdt(shm_call);
	shmdt(shm_return);
}


JNIEXPORT void JNICALL Java_it_unisa_ocelot_simulator_CBridge_getEvents
		(JNIEnv *env, jobject self,
				jobject eventHandler, jdoubleArray values, jobjectArray arrays, jdoubleArray pointers) {
	//***********************************************************************
	// JNI STARTUP
	//***********************************************************************
	//Gets the class of the EventHandler instance
	jclass eventHandlerClass = (*env)->GetObjectClass(env, eventHandler);
	jclass cbridge = (*env)->GetObjectClass(env, self);

	jfieldID coreIdField = (*env)->GetFieldID(env, cbridge, "coreId", "I");
	jint coreId = (*env)->GetIntField(env, self, coreIdField);

	//Has the lock on the final passage of the child, when he wants to restart the cycle
	WAIT_PASSAGE();
	_f_ocelot_debug("PARENT: Locked releaser\n",NODEBUGINFO);

	//Gets the "add" method of the EventHandler class
	jmethodID addMethod = (*env)->GetMethodID(env, eventHandlerClass, "add", "(IDD)V");
	jmethodID addCaseMethod = (*env)->GetMethodID(env, eventHandlerClass, "addCase", "(IDZ)V");

	//TODO ATTENTION: modify here in order to make everything work properly with multithreading
	// In particular, modify so that shm_call used here is the shm_call specific of coreId process

	shm_call = shmat(shared_call_id, 0, 0);
	shm_return = shmat(shared_return_id, 0, SHM_RDONLY);

	if (shm_call < 0 || shm_return < 0) {
		char message[100];
		sprintf(message, "OCELOT ERROR: Unable to attach one of the shared memory segments. Error: %d", errno);
		_f_ocelot_throw_runtimeexception(env, message);
		goto close;
	}

	volatile _T_ocelot_call_memory call_memory = _f_ocelot_shared_call(shm_call);

	int lenValues = (*env)->GetArrayLength(env, values);
	int lenArrays = (*env)->GetArrayLength(env, arrays);
	int lenPointers = (*env)->GetArrayLength(env, pointers);
	MEMSET(call_memory.values, lenValues);
	MEMSET(call_memory.arrays, lenArrays);
	MEMSET(call_memory.pointers, lenPointers);

	(*env)->GetDoubleArrayRegion(env, values, 0, MEMGET(call_memory.values),
			call_memory.data);
	int i;
	for (i = 0; i < MEMGET(call_memory.arrays); i++) {
		jdoubleArray currentArray = (jdoubleArray)(*env)->GetObjectArrayElement(env, arrays, i);

		(*env)->GetDoubleArrayRegion(env, currentArray, 0, OCELOT_ARRAYS_SIZE,
				call_memory.data + MEMGET(call_memory.values) + OCELOT_ARRAYS_SIZE*i);
	}

	(*env)->GetDoubleArrayRegion(env, pointers, 0, MEMGET(call_memory.pointers),
			call_memory.data + MEMGET(call_memory.values) + MEMGET(call_memory.arrays)*OCELOT_ARRAYS_SIZE);

	MEMSET(call_memory.signal, OCELOT_SIGNAL_CALL);

	//Releases the lock for the child, which can start its computation
	_f_ocelot_debug("PARENT: unlocking child...\n",NODEBUGINFO);
	UNLOCK_CHILD();

	_f_ocelot_debug("PARENT: Locking parent...\n",NODEBUGINFO);
	//Waits the moment when the child finishes and releases the lock of the parent
	LOCK_PARENT();
	_f_ocelot_debug("PARENT: Locked parent\n",NODEBUGINFO);

	//Releases the passage. The child waits for the control of the parent.
	RELEASE_PASSAGE();
	_f_ocelot_debug("PARENT: Released passage\n",NODEBUGINFO);

	//Locks the child once again: the child is waiting the release of "PASSAGE"
	LOCK_CHILD();
	_f_ocelot_debug("PARENT: Locked child\n",NODEBUGINFO);

	int status;
	int signal;
	pid_t update = waitpid(child_processes, &status, WNOHANG);
	signal = MEMGET(call_memory.signal);

	if (update < 0) {
		_f_ocelot_throw_runtimeexception(env, "OCELOT ERROR: An unexpected error occured while waiting for the process to terminate!");

		//Respawn the process
		child_processes = _f_ocelot_fork(env, coreId);
		goto finally;
	} else if (update > 0) {
		char message[1000];
		if (WIFEXITED(status)) {
			int exit_status = WEXITSTATUS(status);
			sprintf(message, "OCELOT ERROR: Child process exited unexpectedly. Status: %d", exit_status);
		} else if (WIFSIGNALED(status)) {
			int term_signal = WTERMSIG(status);
			if (!WCOREDUMP(status))
				sprintf(message, "OCELOT ERROR: Child process terminated by a signal. Signal: %d", term_signal);
			else
				sprintf(message, "OCELOT ERROR: Child process terminated by a signal and produced a core dump. Signal: %d", term_signal);
		} else {
			sprintf(message, "OCELOT ERROR: Unknown status. Status: %d", status);
		}

		_f_ocelot_throw_runtimeexception(env, message);

		//Respawn the process
		child_processes = _f_ocelot_fork(env, coreId);

		goto finally;
	} else {
		if (signal == OCELOT_SIGNAL_RESULT) {
			//times = 0; //Break the cycle
		} else if (signal < 0) {
			if (status == OCELOT_ERR_TOOMANYEVENTS) {
				_f_ocelot_throw_runtimeexception(env, "OCELOT ERROR: Events overflow. Please, ensure that there is no infinite loop; try to increase MAX_EVENTS_NUMBER to solve this.");
				goto finally;
			} else {
				_f_ocelot_throw_runtimeexception(env, "OCELOT ERROR: An unexpected error occurred in the native code!");
				goto finally;
			}
		} else if (signal != OCELOT_SIGNAL_CALL) {
			char msg[1000];
			sprintf(msg, "OCELOT ERROR: An unexpected signal in the native code: %d!", signal);
			_f_ocelot_throw_runtimeexception(env, msg);
			goto finally;
		}
	}


	volatile _T_ocelot_return_memory return_memory = _f_ocelot_shared_return(shm_return);
	for (i = 0; i < MEMGET(return_memory.size); i++) {
		volatile _T_ocelot_event event = MEMGET(return_memory.events+i);
		LOG_EVENT(event, loggerParent);
		if (event.kind == OCELOT_KIND_STDEV) {
			(*env)->CallVoidMethod(env, eventHandler, addMethod, event.choice, event.distanceTrue, event.distanceFalse);
		} else {
			(*env)->CallVoidMethod(env, eventHandler, addCaseMethod, event.choice, event.distanceTrue, (jboolean)event.distanceFalse);
		}
	}
	LOG_SEPARATOR(loggerParent);

	_f_ocelot_debug("PARENT: All done!\n",NODEBUGINFO);
finally:
	MEMSET(call_memory.signal, OCELOT_SIGNAL_NOTREADY);

	//Releases the lock of the parent. Now the child is in its initial state (like the parent)
	UNLOCK_PARENT();
	_f_ocelot_debug("PARENT: Unlocked parent!\n",NODEBUGINFO);
close:
	if (shmdt(shm_call) < 0) {
		_f_ocelot_throw_runtimeexception(env, "Unable to detach call memory");
	}
	if (shmdt(shm_return) < 0) {
		_f_ocelot_throw_runtimeexception(env, "Unable to detach return memory");
	}
}

/*
 * Utility that returns a useful representation of the shared call memory.
 */
volatile _T_ocelot_call_memory _f_ocelot_shared_call(volatile void* shm) {
	_T_ocelot_call_memory result;

	result.signal = (unsigned char*)shm;
	result.values = (int*)(result.signal + 1);
	result.arrays = (result.values + 1);
	result.pointers = (result.arrays + 1);
	result.data = (double*)(result.pointers+1);

	return result;
}

/*
 * Utility that returns a useful representation of the shared return memory.
 */
volatile _T_ocelot_return_memory _f_ocelot_shared_return(volatile void* shm) {
	_T_ocelot_return_memory result;

	result.size = (int*)shm;
	result.events = (_T_ocelot_event*)(result.size+1);

	return result;
}


/*
 * Forks and creates a child. This function describes the behavoir of the child, who waits for a signal in call memory
 * and, when received, starts the normal procedure.
 */
pid_t _f_ocelot_fork(JNIEnv* env, int coreId) {
	pid_t pid = fork();
	jnienv = env;

	if (pid == 0) {
		pid_t parent_pid = getppid();
		shm_call = shmat(shared_call_id, 0, 0);
		shm_return = shmat(shared_return_id, 0, 0);

		//Gains control over the parent
		_f_ocelot_debug("CHILD%d: Locking parent...\n",coreId);
		LOCK_PARENT();
		_f_ocelot_debug("CHILD%d: Locked parent!\n",coreId);

		//Waits the parent to release the control of the child
		LOCK_CHILD();
		_f_ocelot_debug("CHILD%d: Locked child!\n",coreId);
		while (kill(parent_pid, 0) == 0) {
			//Note: the check of parent status has to be performed right before the call. This is
			//because it could happen that the resources are released only because the parent
			//process died.
			_f_ocelot_on_signal(coreId);
			//Control of self not needed anymore

			//Releases the control for the parent
			UNLOCK_PARENT();
			_f_ocelot_debug("CHILD%d: Unlocked parent!\n",coreId);

			_f_ocelot_debug("CHILD%d: Waiting passage...\n",coreId);
			//Waits for the parent to complete the reading
			WAIT_PASSAGE();

			UNLOCK_CHILD();
			_f_ocelot_debug("CHILD%d: Unlocked child!\n",coreId);


			//Gains control over the parent
			_f_ocelot_debug("CHILD%d: Locking parent...\n",coreId);
			LOCK_PARENT();
			_f_ocelot_debug("CHILD%d: Locked parent!\n",coreId);

			RELEASE_PASSAGE();
			_f_ocelot_debug("CHILD%d: Passage done!\n",coreId);

			//Waits that the parent releases the control of self
			LOCK_CHILD();
			_f_ocelot_debug("CHILD%d: Locked child!\n",coreId);
		}

		_f_ocelot_debug("CHILD KILLED!", NODEBUGINFO);

		shmdt(shm_call);
		shmdt(shm_return);

		shmctl(shared_call_id, IPC_RMID, NULL);
		shmctl(shared_return_id, IPC_RMID, NULL);

		exit(0);
	}

	return pid;
}

void _f_ocelot_on_signal(int coreId) {
	volatile _T_ocelot_call_memory call_memory = _f_ocelot_shared_call(shm_call);

	volatile int valuesN = MEMGET(call_memory.values);
	volatile int arraysN = MEMGET(call_memory.arrays);
	volatile int pointersN = MEMGET(call_memory.pointers);

	volatile double* values = call_memory.data;
	volatile double* arrays = call_memory.data + valuesN;
	volatile double* pointers = call_memory.data + valuesN + arraysN*OCELOT_ARRAYS_SIZE;

	int result = _f_ocelot_do_stuff(coreId, jnienv, valuesN, arraysN, pointersN, values, arrays, pointers);

	switch (result) {
	case 0:
		MEMSET(call_memory.signal, OCELOT_SIGNAL_RESULT);
		break;
	default:
		MEMSET(call_memory.signal, -result);
		break;
	}
}

int _f_ocelot_do_stuff(int coreId, JNIEnv* env, int valuesN, int arraysN, int pointersN,
		volatile double* values, volatile double* arrays, volatile double* pointers) {

	_f_ocelot_init();
	int octypes[] = OCELOT_TYPES;
	_f_ocelot_init_arrays(env, arraysN, arrays, octypes);

	EXECUTE_OCELOT_TEST

	if (OCLIST_SIZE(_v_ocelot_events) > MAX_EVENTS_NUMBER) {
		_f_ocelot_end();
		return OCELOT_ERR_TOOMANYEVENTS;
	}

	volatile _T_ocelot_return_memory return_memory = _f_ocelot_shared_return(shm_return);
	MEMSET(return_memory.size, OCLIST_SIZE(_v_ocelot_events));
	int i;
	for (i = 0; i < OCLIST_SIZE(_v_ocelot_events); i++) {
		_T_ocelot_event event = OCLIST_GET(_v_ocelot_events, i, _T_ocelot_event);
		LOG_EVENT(event, loggerChild);
		memcpy(return_memory.events+i, &event, sizeof(_T_ocelot_event));
	}

	LOG_SEPARATOR(loggerChild);

	_f_ocelot_end();

	return 0;
}

#define OCARRTRANS(type, val) ((type*)(_v_ocelot_pointers[i]))[j] = val;

void _f_ocelot_init_arrays(JNIEnv* env, int arrayN, double* array, int* types) {
	_v_ocelot_pointers = (_t_ocelot_array*)malloc(sizeof(_t_ocelot_array)*arrayN);
	int i, j;
	for (i = 0; i < arrayN; i++) {
		for (j = 0; j < OCELOT_ARRAYS_SIZE; j++) {
			int index = i*OCELOT_ARRAYS_SIZE + j;

			int valueInt = (int)array[index];
			double valueDouble = array[index];
			char valueChar = (char)array[index];
			unsigned int valueUInt = (unsigned int)array[index];
			unsigned char valueUChar = (unsigned char)array[index];

			int* _v_ocelot_pointers_int = (int*)(_v_ocelot_pointers[i]);
			double* _v_ocelot_pointers_double = _v_ocelot_pointers[i];
			char* _v_ocelot_pointers_char = (char*)(_v_ocelot_pointers[i]);
			unsigned int* _v_ocelot_pointers_uint = (unsigned int*)(_v_ocelot_pointers[i]);
			unsigned char* _v_ocelot_pointers_uchar = (unsigned char*)(_v_ocelot_pointers[i]);

			switch (types[i]) {
			case TYPE_INT:
				_v_ocelot_pointers_int[j] = valueInt;
				break;
			case TYPE_DOUBLE:
				_v_ocelot_pointers_double[j] = valueDouble;
				break;
			case TYPE_CHAR:
				_v_ocelot_pointers_char[j] = valueChar;
				break;
			case TYPE_UNSIGNEDINT:
				_v_ocelot_pointers_uint[j] = valueUInt;
				break;
			case TYPE_UNSIGNEDCHAR:
				_v_ocelot_pointers_uchar[j] = valueUChar;
				break;
			default:
				_v_ocelot_pointers_double[j] = valueDouble;
				break;
			}
		}
	}
}

jdouble _f_ocelot_numval(JNIEnv* env, jobject object) {
	jclass class = (*env)->FindClass(env, "java/lang/Double");

	jmethodID doubleValue = (*env)->GetMethodID(env, class, "doubleValue", "()D");

	return (*env)->CallDoubleMethod(env, object, doubleValue);
}

void _f_ocelot_throw_runtimeexception(JNIEnv* env, char* message) {
	jclass exClass;
	char* className = "java/lang/RuntimeException" ;

	exClass = (*env)->FindClass(env, className);
	if (exClass == NULL) {
		return;
	}

	(*env)->ThrowNew(env, exClass, message);
}

void _f_ocelot_debug(char* info, int num) {
	return;
	if (num != NODEBUGINFO)
		fprintf(stdout, info, num);
	else
		fprintf(stdout, info);//stderr
}

void _f_ocelot_lock(int fd) {
	struct flock f1;

	f1.l_type = F_WRLCK;
	f1.l_whence = SEEK_SET;
	f1.l_start = 0;
	f1.l_len = 0;
	f1.l_pid = getpid();

	fcntl(fd, F_SETLKW, &f1);
}

void _f_ocelot_unlock(int fd) {
	struct flock f1;

	f1.l_type = F_UNLCK;
	f1.l_whence = SEEK_SET;
	f1.l_start = 0;
	f1.l_len = 0;
	f1.l_pid = getpid();

	fcntl(fd, F_SETLKW, &f1);
}

/****************************************************************************************
 * SHARED MEMORIES
 *
 * RETURN
 *  _____ _____________
 * |SIZE | EVENTS      |
 *  ¯¯¯¯¯ ¯¯¯¯¯¯¯¯¯¯¯¯¯
 *  Size: Number of events (max: MAX_EVENTS_NUMBER)
 *  Events: Array of events
 *
 * CALL
 *  ______ ______ ______ ________ _____________
 * |SIGNAL|VALUES|ARRAYS|POINTERS|DATA         |
 *  ¯¯¯¯¯¯ ¯¯¯¯¯¯ ¯¯¯¯¯¯ ¯¯¯¯¯¯¯¯ ¯¯¯¯¯¯¯¯¯¯¯¯¯
 *
 *  Signal: 0 -> Not ready; 1 -> Call can be performed; 2 -> All completed
 *  Values: Number of values
 *  Arrays: Number of arrays
 *  Pointers: Number of pointers
 *  Data: All the previously declared arrays (values, all the arrays, pointers)
 ***************************************************************************************/
