config.glib2Paths:/usr/include/glib-2.0/,/usr/lib/x86_64-linux-gnu/glib-2.0/include/
config.javaHome:/usr/lib/jvm/java-17-openjdk-amd64
config.systemInclude:/usr/include
config.javaPaths:/usr/lib/jvm/java-17-openjdk-amd64/include/,/usr/lib/jvm/java-17-openjdk-amd64/include/linux/
config.make:make

#############:::::::::::::::::::::::::::::::::UPDATE this::::::::::::::::::::::::::::::::::::::
evaluations.time:60
population.size:200
evaluations.max:2000
#200000 20000 9000000

#############:::::::::::::::::::::::::::::::::UPDATE this::::::::::::::::::::::::::::::::::::::

crossover.probability:0.8
mutation.probability:0.1
mutation.dynamic:false
operators.mutator.metamutator:false
threads:1


test.debug:false
test.ui:false
#############:::::::::::::::::::::::::::::::::UPDATE this::::::::::::::::::::::::::::::::::::::

experiment.output.folder:/home/elson/git/EvInT_2025_experiments/CheckCDG/toy4/outputs/
experiment.results.folder:/home/elson/git/EvInT_2025_experiments/CheckCDG/toy4/results

#############:::::::::::::::::::::::::::::::::UPDATE this::::::::::::::::::::::::::::::::::::::

experiment.results.print:true
experiment.runs:1
experiment.generators:MOSA
experiment.minimization:false
experiment.splitbooleans:true
experiment.dynamic:true
experiment.maxiterforobjective:999999
#experiment.random:false

experiment.optimize:Pairs

experiment.evaluate:Pairs

suite.generator:GenericMosa
#suite.generator:DynamicMcCabe
suite.generator.cascade:Random

suite.generator.algorithm:GeneticAlgorithm
suite.generator.serendipitous:false
suite.generator.budgetmanager:Basic

suite.generator.dmc.seed:true
suite.generator.dmc.seed.size:50

suite.generator.rmc.times:1
#suite.generator.random.limit.tc:100
suite.generator.random.limit.tc:1000000
suite.generator.random.limit.time:-1
suite.generator.random.granularity:1000
suite.minimizer:AdditionalGreedy

#############:::::::::::::::::::::::::::::::::UPDATE this::::::::::::::::::::::::::::::::::::::

test.basedir:/home/elson/git/EvInT_2025_experiments/CheckCDG/toy4/

test.filename:main.c

test.function:main

test.includes:/home/elson/git/EvInT_2025_experiments/CheckCDG/toy4/root.c,/home/elson/git/EvInT_2025_experiments/CheckCDG/toy4/fun1.c,/home/elson/git/EvInT_2025_experiments/CheckCDG/toy4/fun2.c,/home/elson/git/EvInT_2025_experiments/CheckCDG/toy4/fun3.c,/home/elson/git/EvInT_2025_experiments/CheckCDG/toy4/root.h

test.components:fun1,fun2,fun3

test.pairComponents:fun1,fun2;fun2,fun3;fun1,fun3


test.parameters.ranges:0:50 0:50 -20:-10

#############:::::::::::::::::::::::::::::::::UPDATE this::::::::::::::::::::::::::::::::::::::


test.arrays.size:1000
avm.epsilon:0.00001
avm.delta:1 

suite.coverage:0.9843750
#suite.coverage:1.1
