config.glib2Paths:/usr/include/glib-2.0/,/usr/lib/x86_64-linux-gnu/glib-2.0/include/
config.javaHome:/usr/lib/jvm/java-17-openjdk-amd64
config.systemInclude:/usr/include
config.javaPaths:/usr/lib/jvm/java-17-openjdk-amd64/include/,/usr/lib/jvm/java-17-openjdk-amd64/include/linux/
config.make:make

#############:::::::::::::::::::::::::::::::::UPDATE this::::::::::::::::::::::::::::::::::::::
evaluations.time:0
population.size:100
evaluations.max:900000
#############:::::::::::::::::::::::::::::::::UPDATE this::::::::::::::::::::::::::::::::::::::

crossover.probability:0.9
mutation.probability:0.1
mutation.dynamic:false
operators.mutator.metamutator:false
threads:1


test.debug:false
test.ui:false
#############:::::::::::::::::::::::::::::::::UPDATE this::::::::::::::::::::::::::::::::::::::

experiment.output.folder:/home/elson/git/EvInT_2025_experiments/CheckCDG/KCG_EMDM/outputs/
experiment.results.folder:/home/elson/git/EvInT_2025_experiments/CheckCDG/KCG_EMDM/results

#############:::::::::::::::::::::::::::::::::UPDATE this::::::::::::::::::::::::::::::::::::::

experiment.results.print:true
experiment.runs:1
experiment.generators:MOSA
experiment.minimization:false
experiment.splitbooleans:true
experiment.dynamic:false
experiment.maxiterforobjective:999999

experiment.random:false
experiment.optimize:Pairs
experiment.evaluate:Pairs

suite.generator:GenericMosa
#suite.generator:DynamicMcCabe
suite.generator.cascade:Random

suite.generator.algorithm:GeneticAlgorithm
suite.generator.serendipitous:false
suite.generator.budgetmanager:Basic

suite.generator.dmc.seed:true
suite.generator.dmc.seed.size:50

suite.generator.rmc.times:1
#suite.generator.random.limit.tc:100
suite.generator.random.limit.tc:1000000
suite.generator.random.limit.time:-1
suite.generator.random.granularity:1000
suite.minimizer:AdditionalGreedy

#############:::::::::::::::::::::::::::::::::UPDATE this::::::::::::::::::::::::::::::::::::::

test.basedir:/home/elson/git/EvInT_2025_experiments/CheckCDG/KCG_EMDM

test.filename:Root.c

test.function:main

test.components:AddConditionalMsg_ME_Lib_DM_TIM_TMH_TDP_EMDM_CEM,AddUnconditionalEmergencyMsg_ME_Lib_DM_TIM_TMH_TDP_EMDM_UEM_AddUncondMsg,AddUnconditionalMsg_ME_Lib_DM_TIM_TMH_TDP_EMDM_UEM,CheckPresence15_ME_Lib_DM_TIM_TMH_TDP_EMDM_CEM_AddCondMsg,CheckPresence16_ME_Lib_DM_TIM_TMH_TDP_EMDM_UEM_AddUncondMsg,ConditionalEmergencyMessageAcceptance_ME_Lib_DM_TIM_TMH_TDP_EMDM_CEM,ConditionalEmergencyMessage_Updater_ME_Lib_DM_TIM_TMH_TDP_EMDM_CEM,EMDM_Root_ME_Lib_DM_TIM_TMH_TDP_EMDM,RevokeConditionalEmergencyMessage_ME_Lib_DM_TIM_TMH_TDP_EMDM_CEM,RevokeConditionalEmergencyMsg_ME_Lib_DM_TIM_TMH_TDP_EMDM_CEM_RevokeCondMsg,RevokeUnconditionalEmergencyMessage_ME_Lib_DM_TIM_TMH_TDP_EMDM_UEM,RevokeUnconditionalEmergencyMsg_ME_Lib_DM_TIM_TMH_TDP_EMDM_UEM_RevokeUncondMsg,SendConditionalEmergencyMessageAcknowledge_ME_Lib_DM_TIM_TMH_TDP_EMDM_CEM,SendUnconditionalEmergencyMessageAcknowledge_ME_Lib_DM_TIM_TMH_TDP_EMDM_UEM,UnconditionalEmergencyMessage_Updater_ME_Lib_DM_TIM_TMH_TDP_EMDM_UEM

test.pairComponents:EMDM_Root_ME_Lib_DM_TIM_TMH_TDP_EMDM,ConditionalEmergencyMessage_Updater_ME_Lib_DM_TIM_TMH_TDP_EMDM_CEM;EMDM_Root_ME_Lib_DM_TIM_TMH_TDP_EMDM,UnconditionalEmergencyMessage_Updater_ME_Lib_DM_TIM_TMH_TDP_EMDM_UEM;




test.includes:/home/elson/git/EvInT_2025_experiments/CheckCDG/KCG_EMDM/CheckPresence16_ME_Lib_DM_TIM_TMH_TDP_EMDM_UEM_AddUncondMsg.c,/home/elson/git/EvInT_2025_experiments/CheckCDG/KCG_EMDM/RevokeConditionalEmergencyMsg_ME_Lib_DM_TIM_TMH_TDP_EMDM_CEM_RevokeCondMsg.c,/home/elson/git/EvInT_2025_experiments/CheckCDG/KCG_EMDM/ConditionalEmergencyMessageAcceptance_ME_Lib_DM_TIM_TMH_TDP_EMDM_CEM.c,/home/elson/git/EvInT_2025_experiments/CheckCDG/KCG_EMDM/RevokeConditionalEmergencyMessage_ME_Lib_DM_TIM_TMH_TDP_EMDM_CEM.c,/home/elson/git/EvInT_2025_experiments/CheckCDG/KCG_EMDM/SendUnconditionalEmergencyMessageAcknowledge_ME_Lib_DM_TIM_TMH_TDP_EMDM_UEM.c,/home/elson/git/EvInT_2025_experiments/CheckCDG/KCG_EMDM/ConditionalEmergencyMessage_Updater_ME_Lib_DM_TIM_TMH_TDP_EMDM_CEM.c,/home/elson/git/EvInT_2025_experiments/CheckCDG/KCG_EMDM/kcg_consts.c,/home/elson/git/EvInT_2025_experiments/CheckCDG/KCG_EMDM/SendConditionalEmergencyMessageAcknowledge_ME_Lib_DM_TIM_TMH_TDP_EMDM_CEM.c,/home/elson/git/EvInT_2025_experiments/CheckCDG/KCG_EMDM/AddConditionalMsg_ME_Lib_DM_TIM_TMH_TDP_EMDM_CEM.c,/home/elson/git/EvInT_2025_experiments/CheckCDG/KCG_EMDM/kcg_types.c,/home/elson/git/EvInT_2025_experiments/CheckCDG/KCG_EMDM/AddUnconditionalEmergencyMsg_ME_Lib_DM_TIM_TMH_TDP_EMDM_UEM_AddUncondMsg.c,/home/elson/git/EvInT_2025_experiments/CheckCDG/KCG_EMDM/RevokeUnconditionalEmergencyMessage_ME_Lib_DM_TIM_TMH_TDP_EMDM_UEM.c,/home/elson/git/EvInT_2025_experiments/CheckCDG/KCG_EMDM/RevokeUnconditionalEmergencyMsg_ME_Lib_DM_TIM_TMH_TDP_EMDM_UEM_RevokeUncondMsg.c,/home/elson/git/EvInT_2025_experiments/CheckCDG/KCG_EMDM/CheckPresence15_ME_Lib_DM_TIM_TMH_TDP_EMDM_CEM_AddCondMsg.c,/home/elson/git/EvInT_2025_experiments/CheckCDG/KCG_EMDM/EMDM_Root_ME_Lib_DM_TIM_TMH_TDP_EMDM.c,/home/elson/git/EvInT_2025_experiments/CheckCDG/KCG_EMDM/UnconditionalEmergencyMessage_Updater_ME_Lib_DM_TIM_TMH_TDP_EMDM_UEM.c,/home/elson/git/EvInT_2025_experiments/CheckCDG/KCG_EMDM/AddUnconditionalMsg_ME_Lib_DM_TIM_TMH_TDP_EMDM_UEM.c,/home/elson/git/EvInT_2025_experiments/CheckCDG/KCG_EMDM/kcg_consts.h,/home/elson/git/EvInT_2025_experiments/CheckCDG/KCG_EMDM/kcg_types.h,/home/elson/git/EvInT_2025_experiments/CheckCDG/KCG_EMDM/genericDataBase.c,/home/elson/git/EvInT_2025_experiments/CheckCDG/KCG_EMDM/dataBaseForKcg.c,/home/elson/git/EvInT_2025_experiments/CheckCDG/KCG_EMDM/initDataBase.c,/home/elson/git/EvInT_2025_experiments/CheckCDG/KCG_EMDM/basetypes.h,/home/elson/git/EvInT_2025_experiments/CheckCDG/KCG_EMDM/kcg_assign.h,/home/elson/git/EvInT_2025_experiments/CheckCDG/KCG_EMDM/kcg_sensors.h,/home/elson/git/EvInT_2025_experiments/CheckCDG/KCG_EMDM/user_macros.h,/home/elson/git/EvInT_2025_experiments/CheckCDG/KCG_EMDM/genericDataBase.h,/home/elson/git/EvInT_2025_experiments/CheckCDG/KCG_EMDM/dataBaseForKcg.h

test.parameters.ranges:0:2 -2147483648:2147483647 -2147483648:2147483647 -2147483648:2147483647 -2147483648:2147483647 -2147483648:2147483647 -2147483648:2147483647 0:3 0:3 0:3 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:1 0:1 0:65535 0:65535 0:16383 0:255 0:1023 0:4294967295 0:1 0:65535 0:65535 0:15 0:3 -32768:32767 0:3 0:32767 0:2 0:1 0:1 0:65535 0:65535 0:16383 0:255 0:1023 0:4294967295 0:1 0:65535 0:65535 0:15 0:3 -32768:32767 0:3 0:32767 0:2 0:1 0:1 0:65535 0:65535 0:16383 0:255 0:1023 0:4294967295 0:1 0:65535 0:65535 0:15 0:3 -32768:32767 0:3 0:32767 0:2 0:1 0:1 0:65535 0:65535 0:16383 0:255 0:1023 0:4294967295 0:1 0:65535 0:65535 0:15 0:3 -32768:32767 0:3 0:32767 0:2 0:1 0:1 0:65535 0:65535 0:16383 0:255 0:1023 0:4294967295 0:1 0:65535 0:65535 0:15 0:3 -32768:32767 0:3 0:32767 0:2 0:1 0:1 0:65535 0:65535 0:16383 0:255 0:1023 0:4294967295 0:1 0:65535 0:65535 0:15 0:3 -32768:32767 0:3 0:32767 0:2 0:1 0:1 0:65535 0:65535 0:16383 0:255 0:1023 0:4294967295 0:1 0:65535 0:65535 0:15 0:3 -32768:32767 0:3 0:32767 0:2 0:1 0:1 0:65535 0:65535 0:16383 0:255 0:1023 0:4294967295 0:1 0:65535 0:65535 0:15 0:3 -32768:32767 0:3 0:32767 0:2 0:1 0:1 0:65535 0:65535 0:16383 0:255 0:1023 0:4294967295 0:1 0:65535 0:65535 0:15 0:3 -32768:32767 0:3 0:32767 0:2 0:1 0:1 0:65535 0:65535 0:16383 0:255 0:1023 0:4294967295 0:1 0:65535 0:65535 0:15 0:3 -32768:32767 0:3 0:32767 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:1 0:1 0:65535 0:65535 0:16383 0:255 0:1023 0:4294967295 0:1 0:65535 0:65535 0:15 0:2 0:1 0:1 0:65535 0:65535 0:16383 0:255 0:1023 0:4294967295 0:1 0:65535 0:65535 0:15 0:2 0:1 0:1 0:65535 0:65535 0:16383 0:255 0:1023 0:4294967295 0:1 0:65535 0:65535 0:15 0:2 0:1 0:1 0:65535 0:65535 0:16383 0:255 0:1023 0:4294967295 0:1 0:65535 0:65535 0:15 0:2 0:1 0:1 0:65535 0:65535 0:16383 0:255 0:1023 0:4294967295 0:1 0:65535 0:65535 0:15 0:2 0:1 0:1 0:65535 0:65535 0:16383 0:255 0:1023 0:4294967295 0:1 0:65535 0:65535 0:15 0:2 0:1 0:1 0:65535 0:65535 0:16383 0:255 0:1023 0:4294967295 0:1 0:65535 0:65535 0:15 0:2 0:1 0:1 0:65535 0:65535 0:16383 0:255 0:1023 0:4294967295 0:1 0:65535 0:65535 0:15 0:2 0:1 0:1 0:65535 0:65535 0:16383 0:255 0:1023 0:4294967295 0:1 0:65535 0:65535 0:15 0:2 0:1 0:1 0:65535 0:65535 0:16383 0:255 0:1023 0:4294967295 0:1 0:65535 0:65535 0:15 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:2 0:134217727 0:727
#############:::::::::::::::::::::::::::::::::UPDATE this::::::::::::::::::::::::::::::::::::::


test.arrays.size:1000
avm.epsilon:0.00001
avm.delta:1 

suite.coverage:0.9843750
#suite.coverage:1.1
