package it.unisa.ocelot.genetic.objectives.chains;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.*;
import java.util.stream.Collectors;

import it.unisa.ocelot.c.cdg.CDG;
import it.unisa.ocelot.c.cdg.CDGNode;
import it.unisa.ocelot.c.cdg.ControlDependenceEdge;
import it.unisa.ocelot.c.cfg.CFG;
import it.unisa.ocelot.c.cfg.nodes.CFGNode;
import it.unisa.ocelot.conf.ConfigManager;
import it.unisa.ocelot.genetic.edges.FunBranchNameAndFitness;
import it.unisa.ocelot.genetic.objectives.GenericObjective;
import it.unisa.ocelot.genetic.solutions.CacheAccessor;
import it.unisa.ocelot.genetic.solutions.GenericSolution;
/**
 * EVINT_TOOL_MARKER
 * This class is used by the EvInT (Evolutionary Integration Testing) tool.
 */
public class BranchChainManager {
	// Default filename for CDG output. The actual path is resolved lazily using test.basedir from ConfigManager.
	private static final String DEFAULT_CDG_FILENAME = "cdg_output.txt";
	// Filename for CFG+CDG human-readable dump (same directory as DEFAULT_CDG_FILENAME)
	private static final String DEFAULT_CFG_CDG_FILENAME = "cfg_cdg.txt";

	// One-time-per-JVM guard: delete old CDG output file on first call to getOutputFile()
	private static volatile boolean OUTPUT_FILE_CLEANED = false;
	// One-time-per-JVM guard: truncate old cfg_cdg file on first call
	private static volatile boolean CFG_CDG_CLEANED = false;

	private static Map<String, Map<String, List<BranchChain>>> allBranchChainsSaved = new HashMap<>();
	private static List<BranchChainPair> allPairs = new ArrayList<>();
	private static List<GenericObjective> generatedBranchChainObjectives;

	// Returns (and possibly makes) all the objectives.
	public static List<GenericObjective> loadObjectives() {
		if (generatedBranchChainObjectives == null) {
			List<GenericObjective> objectives = new ArrayList<GenericObjective>();
			int objectiveID = 0;
			for (BranchChainPair pair : allPairs) {
				BranchChainPairObjective objective = new BranchChainPairObjective(objectiveID, pair);
				objectives.add(objective);
				objectiveID++;
			}
			generatedBranchChainObjectives = objectives;
			System.out.println(generatedBranchChainObjectives);
		}
		return generatedBranchChainObjectives;
	}

	private ConfigManager config;
	private Map<String, List<BranchChain>> allBranchChains;

	// instance-level output files (created lazily so we can read ConfigManager.test.basedir at runtime)
	private File outputFile = null;
	private File cfgCdgFile = null;

	public BranchChainManager() {
		this.allBranchChains = new HashMap<String, List<BranchChain>>();
	}

	/**
	 * Builds the CDG from a CFG for a unit component and generates all the 
	 * branch chains.
	 * 
	 * @param cfg a {@link CFG}.
	 * @param tempUnitComponent a {@link String}, the name of a unit component.
	 * @throws Exception
	 */
	public void process(CFG cfg, String tempUnitComponent) throws Exception {
		this.config = ConfigManager.getInstance();
		//build the CDG graph from CFG
		// CRITICAL: Reset CFGNode and CDGNode IDs for each unit component
		CFGNode.reset();      
		CDG.resetNodeIds();   
		CDG cdg = new CDG(cfg);
		System.out.println("Extracting branch-chains for component: " + tempUnitComponent);
		cdg.buildCDG();
		StringBuilder cdgSummary= cdg.printSummary();
		appendLine(cdgSummary.toString());

		CDGBranchPathCollector cdgVisit = new CDGBranchPathCollector(cdg,tempUnitComponent,allBranchChains);
		cdgVisit.collect();

		try {
			writeCfgAndCdg(cfg, cdg, tempUnitComponent);
		} catch (Exception e) {
			System.err.println("Warning: failed to write cfg_cdg dump: " + e.getMessage());
		}
		StringBuilder bctextual= cdgVisit.printBranchChains("NODE Chains",this.allBranchChains);
		appendLine(bctextual.toString());

		//We need to minimized the branch chains
		Map<String, List<BranchChain>> filteredMap = MinimizedAndSaveBranchChains(tempUnitComponent);
		StringBuilder minBCtextual= cdgVisit.printBranchChains("MINIMIZED Node-Chains",filteredMap);
		appendLine(minBCtextual.toString());

	}
	private Map<String, List<BranchChain>> MinimizedAndSaveBranchChains(String tempUnitComponent) {
		//TODO we need to verify the branch numbers generated by the instrumentation() and branch numbers generated by the cdgVisit.collect();

		// 1. Filter the current map to remove redundant branch chains
		Map<String, List<BranchChain>> filteredMap = filterBranchChainsMap(this.allBranchChains);
		
		// 2. Sort and Rename the remaining chains sequentially per component group
		filteredMap.forEach((innerKey, branchChainsList) -> {
			// OPTION A: Sort by Leaf Node ID so the chains are ordered by execution sequence
			branchChainsList.sort((a, b) -> Integer.compare(a.getLeafNode().getId(), b.getLeafNode().getId()));
			// Rename sequentially
			for (int i = 0; i < branchChainsList.size(); i++) {
				BranchChain chain = branchChainsList.get(i);
				// Construct new sequential label, e.g., "fun3:branchChain1", "fun3:branchChain2"
				String newLabel = tempUnitComponent + ":branchChain" + (i + 1);
				chain.setLabel(newLabel); // Ensure your BranchChain class has this setter
			}
		});
		
		// 2. Save the newly created, filtered map snapshot
		allBranchChainsSaved.put(tempUnitComponent, filteredMap);
		
		// 3. Clear the working instance for the next iteration
		this.allBranchChains.clear();
		
		System.out.println("--------------------------------------------");
		return filteredMap;
	}
	
	/**
	 * Iterates through the inner lists of the map and filters out repeating/redundant branch chains.
	 */
	private Map<String, List<BranchChain>> filterBranchChainsMap(Map<String, List<BranchChain>> rawMap) {
		Map<String, List<BranchChain>> filteredResultMap = new HashMap<>();

		rawMap.forEach((innerKey, branchChainsList) -> {
			if (branchChainsList == null || branchChainsList.isEmpty()) {
				filteredResultMap.put(innerKey, new ArrayList<>());
				return; 
			}

			// --- Step A: Signature generation & base deduplication ---
			Map<String, BranchChain> uniquePaths = new HashMap<>();
			for (BranchChain chain : branchChainsList) {
				String logicSig = chain.getPath().stream()
						.filter(PathStep::hasBranchCondition)
						.map(PathStep::getBranchLabel)
						.collect(Collectors.joining("->"));

				String fullSig = logicSig.isEmpty() ? "EMPTY_BRANCH" : logicSig;

				// Keep the chain with the deeper/longer execution path if signatures match
				if (!uniquePaths.containsKey(fullSig) ||
						chain.getPath().size() > uniquePaths.get(fullSig).getPath().size()) {
					uniquePaths.put(fullSig, chain);
				}
			}

			// --- Step B: Sort by descending path size ---
			List<BranchChain> filtered = new ArrayList<>(uniquePaths.values());
			filtered.sort((a, b) -> Integer.compare(b.getPath().size(), a.getPath().size()));

			// --- Step C: Logical prefix / redundancy check ---
			List<BranchChain> finalChains = new ArrayList<>();
			for (BranchChain candidate : filtered) {
				boolean redundant = false;
				for (BranchChain existing : finalChains) {
					if (isPathCovered(candidate, existing)) {
						redundant = true;
						break;
					}
				}
				if (!redundant) {
					finalChains.add(candidate);
				}
			}

			// Save the clean, filtered list back to our new map structure
			filteredResultMap.put(innerKey, finalChains);
		});

		return filteredResultMap;
	}

	/**
	 * Checks if the candidate's logical branch sequence is completely 
	 * covered in the same order by an existing, longer branch sequence.
	 */
	private boolean isPathCovered(BranchChain candidate, BranchChain existing) {
		// Extract the sequence of branch labels for both
		List<String> candLabels = candidate.getPath().stream()
				.filter(PathStep::hasBranchCondition)
				.map(PathStep::getBranchLabel)
				.collect(Collectors.toList());

		List<String> existLabels = existing.getPath().stream()
				.filter(PathStep::hasBranchCondition)
				.map(PathStep::getBranchLabel)
				.collect(Collectors.toList());

		// An empty branch chain is technically covered by anything
		if (candLabels.isEmpty()) return true;
		// A longer chain cannot be covered by a shorter chain
		if (candLabels.size() > existLabels.size()) return false;

		// Two-pointer approach to verify ordered sub-sequence containment
		int candIdx = 0;
		int existIdx = 0;

		while (candIdx < candLabels.size() && existIdx < existLabels.size()) {
			if (candLabels.get(candIdx).equals(existLabels.get(existIdx))) {
				candIdx++; // Match found, move to next candidate label
			}
			existIdx++; // Always move forward in the longer existing path
		}

		// If we matched every single label in the candidate, it is fully covered
		return candIdx == candLabels.size();
	}
	
	/** Helper: append a single line to the cdg output file. Ensures newline termination and closes the writer.
	 * Using a small helper keeps all writes consistent and avoids missing newlines.
	 */
	private void appendLine(String line) {
		try (BufferedWriter writer = new BufferedWriter(new FileWriter(getOutputFile(), true))) {
			if (line == null) line = "";
			writer.write(line);
			writer.write(System.lineSeparator());
		} catch (IOException e) {
			System.err.println("Error writing CDG file: " + e.getMessage());
		}
	}

	/**
	 * Lazily create and return the File used to write CDG output. Prefer the configured test.basedir
	 * (ConfigManager.getTestBasedir()). If config is not available, attempt to obtain the ConfigManager
	 * instance; otherwise fall back to current working directory (./).
	 *
	 * Additionally: on the first call per JVM run, delete any existing CDG output file so each run starts
	 * with a clean file. Also ensure the parent directory exists.
	 */
	private File getOutputFile() {
		if (this.outputFile != null)
			return this.outputFile;

		String baseDir = "./";
		if (this.config != null) {
			baseDir = this.config.getTestBasedir();
		} else {
			try {
				ConfigManager cfg = ConfigManager.getInstance();
				baseDir = cfg.getTestBasedir();
			} catch (IOException e) {
				// ignore and use fallback
			}
		}

		if (baseDir == null || baseDir.isEmpty())
			baseDir = "./";
		if (!baseDir.endsWith("/"))
			baseDir = baseDir + "/";

		// Ensure we delete any old CDG output file only once per JVM run.
		if (!OUTPUT_FILE_CLEANED) {
			File candidate = new File(baseDir + DEFAULT_CDG_FILENAME);
			try {
				// Ensure parent directory exists
				File parent = candidate.getParentFile();
				if (parent != null && !parent.exists()) {
					parent.mkdirs();
				}

				if (candidate.exists()) {
					boolean deleted = candidate.delete();
					if (!deleted) {
						System.err.println("Warning: unable to delete existing CDG output file: " + candidate.getAbsolutePath());
					}
				}
			} catch (SecurityException se) {
				System.err.println("Warning deleting CDG output file: " + se.getMessage());
			} finally {
				OUTPUT_FILE_CLEANED = true;
			}
		}

		this.outputFile = new File(baseDir + DEFAULT_CDG_FILENAME);
		return this.outputFile;
	}

	/**
	 * Lazily create and return the File used to write the CFG+CDG human-readable dump (cfg_cdg.txt).
	 * It uses the same base directory as the CDG output file. On the first call per JVM run it truncates
	 * existing file (deletes it) so each execution starts clean; subsequent calls append.
	 */
	private File getCfgCdgFile() {
		if (this.cfgCdgFile != null)
			return this.cfgCdgFile;

		// Reuse logic to find base dir (same as getOutputFile)
		String baseDir = "./";
		if (this.config != null) {
			baseDir = this.config.getTestBasedir();
		} else {
			try {
				ConfigManager cfg = ConfigManager.getInstance();
				baseDir = cfg.getTestBasedir();
			} catch (IOException e) {
				// ignore and use fallback
			}
		}

		if (baseDir == null || baseDir.isEmpty())
			baseDir = "./";
		if (!baseDir.endsWith("/"))
			baseDir = baseDir + "/";

		File candidate = new File(baseDir + DEFAULT_CFG_CDG_FILENAME);
		try {
			// Ensure parent directory exists
			File parent = candidate.getParentFile();
			if (parent != null && !parent.exists()) {
				parent.mkdirs();
			}

			// On first call, truncate/delete existing file to start fresh for this JVM run
			if (!CFG_CDG_CLEANED) {
				if (candidate.exists()) {
					boolean deleted = candidate.delete();
					if (!deleted) {
						System.err.println("Warning: unable to delete existing cfg_cdg file: " + candidate.getAbsolutePath());
					}
				}
				CFG_CDG_CLEANED = true;
			}
		} catch (SecurityException se) {
			System.err.println("Warning handling cfg_cdg file: " + se.getMessage());
		}

		this.cfgCdgFile = candidate;
		return this.cfgCdgFile;
	}

	/**
	 * Write a human-readable dump of the provided CFG and CDG to cfg_cdg.txt in the same directory as cdg_output.txt.
	 * The file is truncated once per JVM run (first call) and subsequent calls append. The output contains clear
	 * headings and labelled node/edge entries for easy human inspection.
	 *
	 * @param cfg The control-flow graph to dump
	 * @param cdg The control-dependence graph to dump
	 * @param componentName Logical name of the component/function being dumped (included in headings)
	 */
	public void writeCfgAndCdg(CFG cfg, CDG cdg, String componentName) {
		File out = getCfgCdgFile();
		try (BufferedWriter writer = new BufferedWriter(new FileWriter(out, true))) {
			writer.write("");
			writer.newLine();
			//Enable the follow code to get the CFG informations.
			/*writer.write("========================= CFG: " + componentName + " =====================");
            writer.newLine();

            // Print CFG nodes
            writer.write("-- NODES (id: textual content) --");
            writer.newLine();
            List<CFGNode> nodeList = new ArrayList<>(cfg.vertexSet());
            // sort by id for stable output
            Collections.sort(nodeList);
            for (CFGNode node : nodeList) {
                writer.write("Node " + node.getId() + ":");
                writer.newLine();
                String[] lines = node.toString().split("\r?\n");
                for (String ln : lines) {
                    writer.write("    " + ln);
                    writer.newLine();
                }
            }

            // Print CFG edges
            writer.write("-- EDGES (sourceId -> targetId : label [objectiveID]) --");
            writer.newLine();
            // iterate edges in stable order by sourceId then targetId
            List<Object> edges = new ArrayList<>(cfg.edgeSet());
            edges.sort((o1, o2) -> {
                it.unisa.ocelot.c.cfg.edges.LabeledEdge e1 = (it.unisa.ocelot.c.cfg.edges.LabeledEdge)o1;
                it.unisa.ocelot.c.cfg.edges.LabeledEdge e2 = (it.unisa.ocelot.c.cfg.edges.LabeledEdge)o2;
                CFGNode s1 = cfg.getEdgeSource(e1);
                CFGNode s2 = cfg.getEdgeSource(e2);
                int cmp = Integer.compare(s1.getId(), s2.getId());
                if (cmp != 0) return cmp;
                CFGNode t1 = cfg.getEdgeTarget(e1);
                CFGNode t2 = cfg.getEdgeTarget(e2);
                return Integer.compare(t1.getId(), t2.getId());
            });
            for (Object eo : edges) {
                it.unisa.ocelot.c.cfg.edges.LabeledEdge e = (it.unisa.ocelot.c.cfg.edges.LabeledEdge)eo;
                CFGNode s = cfg.getEdgeSource(e);
                CFGNode t = cfg.getEdgeTarget(e);
                String lbl = e.getLabel() == null ? "" : e.getLabel().toString();
                writer.write("Edge " + s.getId() + " -> " + t.getId() + " : '" + lbl + "' [objID=" + e.getObjectiveID() + "]");
                writer.newLine();
            }
			 */
			// Print CDG
			writer.write("");
			writer.newLine();
			writer.write("========================= CDG: " + componentName + " =====================");
			writer.newLine();

			// CDG nodes
			writer.write("-- CDG NODES (cdgId -> original CFG id : label preview) --");
			writer.newLine();
			List<CDGNode> cdgNodes = new ArrayList<>(cdg.vertexSet());
			cdgNodes.sort(Comparator.comparingInt(CDGNode::getId));
			for (CDGNode cn : cdgNodes) {
				String preview = cn.getLabel() == null ? "" : cn.getLabel().replaceAll("\r?\n", " ");
				preview = cn.getLabel() == null ? "" : cn.getLabel().replaceAll("\r?\n", " ").replaceAll("^\\d+:\\s*", "");
				writer.write("CDGNode " + cn.getId() + " -> "+ preview);
				writer.newLine();
			}

			// CDG edges
			writer.write("-- CDG EDGES (sourceCdgId -> targetCdgId : label) --");
			writer.newLine();
			List<ControlDependenceEdge> cdgEdges = new ArrayList<>(cdg.edgeSet());
			for (ControlDependenceEdge ce : cdgEdges) {
				CDGNode s = cdg.getEdgeSource(ce);
				CDGNode t = cdg.getEdgeTarget(ce);
				String label = (ce == null) ? "FLOW" : ce.toString();
				writer.write("CDGEdge " + (s == null ? "?" : s.getId()) + " -> " + (t == null ? "?" : t.getId()) + " : '" + label + "'");
				writer.newLine();
			}

			writer.write("-- END DUMP for: " + componentName + " --");
			writer.newLine();
			writer.flush();
		} catch (IOException e) {
			System.err.println("Error writing cfg_cdg file: " + e.getMessage());
		}
	}



	public void generatePairsForBranchChains() {

		// ensure config available
		if (this.config == null) {
			try {
				this.config = ConfigManager.getInstance();
			} catch (IOException e) {
				System.err.println("Unable to load configuration for pair generation: " + e.getMessage());
				appendLine("ERROR: Unable to load configuration: " + e.getMessage());
				return;
			}
		}

		// Get component pairs from configuration (preserves duplicates)
		List<ComponentPair> componentPairs = this.config.getPairComponents();
		appendLine("");
		appendLine("============================ GENERATING BRANCH-CHAIN PAIRS ============================");
		appendLine("Component pairs from configuration: " + componentPairs.size());
		for (ComponentPair componentPair : componentPairs) {
			String component1 = componentPair.getComponent1();
			String component2 = componentPair.getComponent2();

			System.out.println("\n\nProcessing pair: " + component1 + " <-> " + component2);
			appendLine("\n\n");
			appendLine("Processing pair: " + component1 + " <-> " + component2);

			List<BranchChain> chains1 = allBranchChainsSaved.containsKey(component1) 
					? allBranchChainsSaved.get(component1).get(component1) 
							: Collections.emptyList();

			List<BranchChain> chains2 = allBranchChainsSaved.containsKey(component1) 
					? allBranchChainsSaved.get(component2).get(component2) 
							: Collections.emptyList();
			// Validate both components exist
			if (chains1 == null) {
				System.err.println("WARNING: Component '" + component1 + "' not found in processed chains");
				appendLine("WARNING: Component '" + component1 + "' not found in processed chains");
				continue;
			}
			if (chains2 == null) {
				System.err.println("WARNING: Component '" + component2 + "' not found in processed chains");
				appendLine("WARNING: Component '" + component2 + "' not found in processed chains");
				continue;
			}

			// Generate Cartesian product
			List<BranchChainPair> pairsForThisComponent = generateCartesianProduct(
					component1, chains1, 
					component2, chains2
					);

			allPairs.addAll(pairsForThisComponent);
			// write the generated pairs in a readable form (one per line) instead of relying on List.toString()
			appendLine("Generated pairs for: " + component1 + " <-> " + component2 + " (count=" + pairsForThisComponent.size() + ")");
			int counter = 1;
			for (BranchChainPair p : pairsForThisComponent) {
				if(p.toString() != null && !p.toString().isEmpty()) {
					appendLine("Branch Chain:  "+ counter + p.toString());
					++counter;
				}
			}
			System.out.println("  Generated " + pairsForThisComponent.size() + " branch-chain pairs");
			appendLine("  Generated " + pairsForThisComponent.size() + " branch-chain pairs");
		}

		System.out.println("\nTotal branch-chain pairs generated: " + allPairs.size());
		appendLine("Total branch-chain pairs generated: " + allPairs.size());
	}

	/**
	 * Generates Cartesian product of branch-chains between two components.
	 *
	 * @param component1 First component name
	 * @param chains1 Branch-chains of first component
	 * @param component2 Second component name
	 * @param chains2 Branch-chains of second component
	 * @return List of all possible pairs
	 */
	private List<BranchChainPair> generateCartesianProduct(
			String component1, List<BranchChain> chains1,
			String component2, List<BranchChain> chains2) {

		List<BranchChainPair> pairs = new ArrayList<>();

		// Cartesian product: for each chain in component1, pair with each chain in component2
		for (BranchChain chain1 : chains1) {
			for (BranchChain chain2 : chains2) {
				BranchChainPair pair = new BranchChainPair(
						component1, chain1,
						component2, chain2
						);
				pairs.add(pair);
			}
		}

		return pairs;
	}

	public static void cacheFitnessValues(GenericSolution solution) {
		HashMap<String, Double> fitnessMap = new HashMap<>();

		// Fills fitnessMap with the data from the fitnessValues.txt file
		try (BufferedReader f_Val_File = new BufferedReader(new FileReader("./fitnessValues.txt"))) {//TODO trace.txt
			String lineBr = f_Val_File.readLine();
			while (lineBr != null) {
				FunBranchNameAndFitness infoFromLinebr = readInfoFromLine(lineBr);
				if (fitnessMap.containsKey(infoFromLinebr.getFunBranchName()) && fitnessMap.get(infoFromLinebr.getFunBranchName()) < infoFromLinebr.getCurrFitnessVal()) {
					// Do nothing
				} else {
					fitnessMap.put(infoFromLinebr.getFunBranchName(), infoFromLinebr.getCurrFitnessVal());
				}
				lineBr = f_Val_File.readLine();
			}
		} catch (IOException e) {
			System.err.println("Error reading fitnessValues.txt file: " + e.getMessage());
		}

		// updates the solution
		solution.update(fitnessMap);
	}

	private static FunBranchNameAndFitness readInfoFromLine(String lineBr) {
		String listOfItems[] = lineBr.split(";");
		String fName = listOfItems[0];
		String branchName = listOfItems[1];
		String fitnessVal = listOfItems[2];
		String fun_BranchName = fName + ":" + branchName;
		fitnessVal = fitnessVal.replace(",", ".");
		double currFitness = Double.parseDouble(fitnessVal);
		if (currFitness > 1)
			System.err.println("Wrong fitness value! Branch:" + fun_BranchName + " Fitness:" + currFitness);
		FunBranchNameAndFitness infoFromLinebr = new FunBranchNameAndFitness(fun_BranchName, currFitness);
		return infoFromLinebr;
	}
}